// -- All Barat Images --------------------------------------------------------
// Auto-generated by tools/get-drive-images.js  (2026-03-25)
// Source folder: BARAT  (555 images)
const images = [
  'https://lh3.googleusercontent.com/d/1UuFl6ftIE5th5yBFJRkXKwniifph_nEH',  // _DSC2162.JPG
  'https://lh3.googleusercontent.com/d/1rZTEKg3gDdzrtAJDfrjo2fCyum9n1GbX',  // _DSC2163.JPG
  'https://lh3.googleusercontent.com/d/1pD6szgpznp4p6BhvIFYjJBf_siludbES',  // _DSC2164.JPG
  'https://lh3.googleusercontent.com/d/1cwkC77ILFx8Cf2_wvQltU9hTvh6aPSjA',  // _DSC2165.JPG
  'https://lh3.googleusercontent.com/d/1O7qFigoQuOsDQLCgOSTYuuXbacTJ9xoF',  // _DSC2166.JPG
  'https://lh3.googleusercontent.com/d/1TNceUC_63hF9IvKzpmEtMm-nISW_13Lx',  // _DSC2167.JPG
  'https://lh3.googleusercontent.com/d/11-innW68SJIaUVNu0OH_7sPZWdicc-aY',  // _DSC2168.JPG
  'https://lh3.googleusercontent.com/d/1nZq2k91haab7m1ZS9n5LwVIQCovNHJVQ',  // _DSC2169.JPG
  'https://lh3.googleusercontent.com/d/1RVWpZ-EEgiaGY0bSq7dvEfl7t2_d1XCq',  // _DSC2170.JPG
  'https://lh3.googleusercontent.com/d/1sBynnPrckY9vxXOJNnp2y775P46IBbgh',  // _DSC2174.JPG
  'https://lh3.googleusercontent.com/d/1a9SBu8bo9s1EPTGdb70oaJfDvYi5IsPB',  // _DSC2175.JPG
  'https://lh3.googleusercontent.com/d/1PCdJde3iSBXkgC_AqP6rJV0m19bQ5AC_',  // _DSC2178.JPG
  'https://lh3.googleusercontent.com/d/1hi_80vvkMTgrSmCyIdg6JuSk4Q2_Ccvo',  // _DSC2180.JPG
  'https://lh3.googleusercontent.com/d/1YA_MlBFODyVND8OTLNUhWz_s5H6_cvpK',  // _DSC2181.JPG
  'https://lh3.googleusercontent.com/d/1eWEboB7UzBpVjAxkMjhzj18ueeeisShN',  // _DSC2182.JPG
  'https://lh3.googleusercontent.com/d/1m976DMNLA8i8c_hDN8dzUOJCa6L7hk26',  // _DSC2183.JPG
  'https://lh3.googleusercontent.com/d/18HvMv4xM0DqiAJzl6hibAsAUpDi9XWo-',  // _DSC2185.JPG
  'https://lh3.googleusercontent.com/d/13MnFfYKC29tvmiXAuFXPZoHyFXOe6jk0',  // _DSC2186.JPG
  'https://lh3.googleusercontent.com/d/1LpjNrXfk5g0pw6P8PLVZ_r-XWQB2L977',  // _DSC2187.JPG
  'https://lh3.googleusercontent.com/d/1i4Xb06Psi6wzebWrDYpC5PNCqWAL8G17',  // _DSC2190.JPG
  'https://lh3.googleusercontent.com/d/1AGbSIFTe7awxANxlWBATvMozm-Nu2iJq',  // _DSC2191.JPG
  'https://lh3.googleusercontent.com/d/1vHGywC_i39sHJWXdtb5EIuQmdS4Wp9vL',  // _DSC2196.JPG
  'https://lh3.googleusercontent.com/d/1O-RANTUncIpZSqitg236qFGS1OxEQeHI',  // _DSC2197.JPG
  'https://lh3.googleusercontent.com/d/17wLXlLvF6vr2nYoTu3KBVShazadOA8Ab',  // _DSC2198.JPG
  'https://lh3.googleusercontent.com/d/1slWkSQpma_Xz0F1rbl102TqBkbZzpSLy',  // _DSC2201.JPG
  'https://lh3.googleusercontent.com/d/1L7l7YG4K18WmIqKYGIoem05mmNHHT5Gk',  // _DSC2204.JPG
  'https://lh3.googleusercontent.com/d/133nqrqV0qEpH6INkamtfdyOMCoPved0-',  // _DSC2207.JPG
  'https://lh3.googleusercontent.com/d/1JwtzzHNUrnCeOJoyk-zEP3tOr3cSLQm7',  // _DSC2214.JPG
  'https://lh3.googleusercontent.com/d/1CoVGXcQdYjETvZNYHvaqgMiEkiB1x33K',  // _DSC2215.JPG
  'https://lh3.googleusercontent.com/d/19mHZ8_eEUJTM4oFDES1bP4wdwbbGTk39',  // _DSC2216.JPG
  'https://lh3.googleusercontent.com/d/1IoHxkPw9AR67n1kI5HCdNDztGLLu18cU',  // _DSC2217.JPG
  'https://lh3.googleusercontent.com/d/16NULk3KOLgyKsydfDsjW97Ka1lLApbtL',  // _DSC2218.JPG
  'https://lh3.googleusercontent.com/d/14OHKywuJxi4cvLuPN8OtlpGeMCaELZuL',  // _DSC2220.JPG
  'https://lh3.googleusercontent.com/d/1BoB-Cg9AUQRtH-9oMJP6HvmrXjGAd_S6',  // _DSC2248.JPG
  'https://lh3.googleusercontent.com/d/1s9BC7lLDLtbusp371CwZwgPJ0H_H3Ki7',  // _DSC2260.JPG
  'https://lh3.googleusercontent.com/d/1qLo0EFD9nZxHKBmE2-39diLKFSSCoQrI',  // _DSC2261.JPG
  'https://lh3.googleusercontent.com/d/1Cp1Vv3WtbZNVnilQlS5gySGwQtOkI2iL',  // _DSC2263.JPG
  'https://lh3.googleusercontent.com/d/1uoLM_XjDr2SsifmkypVyXrNOHVv3S6LQ',  // _DSC2268.JPG
  'https://lh3.googleusercontent.com/d/1F2LZkFBzszPsTel-MYlkGzwPosNZeiur',  // _DSC2275.JPG
  'https://lh3.googleusercontent.com/d/1BiTWUQvPMpON4_qsqQZbP9yPT0Eqd__f',  // _DSC2276.JPG
  'https://lh3.googleusercontent.com/d/1J5VIhMRRevb67RS9Sh2VjZdWlbPJrDtZ',  // _DSC2277.JPG
  'https://lh3.googleusercontent.com/d/1ExuYRsH00G7gfmsGa65ItbyIUktQqQy2',  // _DSC2279.JPG
  'https://lh3.googleusercontent.com/d/1yp8QqsLCBG5StjJCDtU3g3tNqKO3i1V6',  // _DSC2280.JPG
  'https://lh3.googleusercontent.com/d/19sm8QzOBoFQcZx3TgiDyxKtOboNuWlmc',  // _DSC2281.JPG
  'https://lh3.googleusercontent.com/d/1RxhbiLxDbjBsIGCd06UOzHJCKYluPz4R',  // _DSC2282.JPG
  'https://lh3.googleusercontent.com/d/1-4UcJPRm21n8abizCHtm09rN-jk-3uJK',  // _DSC2283.JPG
  'https://lh3.googleusercontent.com/d/1zHC8RTeWm8o02sQ872xo9Rc7Qe7BfI26',  // _DSC2285.JPG
  'https://lh3.googleusercontent.com/d/1Cb-7RyWAiC-kSKFCFmn7Zi6DXzSTJyHG',  // _DSC2291.JPG
  'https://lh3.googleusercontent.com/d/1ANlej2dmlZ3SDBNubvE_MrZKs5BUZj9m',  // _DSC2296.JPG
  'https://lh3.googleusercontent.com/d/1JWMzM2kMBi7ytCcC8kLallnCNefn1r1-',  // _DSC2297.JPG
  'https://lh3.googleusercontent.com/d/1Vlt2SpNaK2yH6ulGrW69NiUUHnONq4zt',  // _DSC2300.JPG
  'https://lh3.googleusercontent.com/d/1OvG5ioWtvJxCm5prvDW6JLsFPnU8go0g',  // _DSC2302.JPG
  'https://lh3.googleusercontent.com/d/1fFHu4Y-Jqmz79MxvDCfKi_VPADuXY1DY',  // _DSC2303.JPG
  'https://lh3.googleusercontent.com/d/17C9wl6bsk--PtGG_aRLrFdOw60VsJ7_H',  // _DSC2304.JPG
  'https://lh3.googleusercontent.com/d/1Oj7EffPYLXV__QTSsB_iKa7KTIAeEfWY',  // _DSC2305.JPG
  'https://lh3.googleusercontent.com/d/1ImsfBXR75kxlBnF64KL_F4X5rRUfyJZw',  // _DSC2306.JPG
  'https://lh3.googleusercontent.com/d/1bbnR4if2gyegvadpUN-YZWP5DmhodVtg',  // _DSC2308.JPG
  'https://lh3.googleusercontent.com/d/1STNmOCGsNOe6AkflQJyKcRJTEGJ_tU4q',  // _DSC2309.JPG
  'https://lh3.googleusercontent.com/d/1zoEpeenO6kZt3_7fNXIJRrE3NacTea00',  // _DSC2310.JPG
  'https://lh3.googleusercontent.com/d/1NpyEGrww4PqVC2q_UCzXFP99IPrk_vn_',  // _DSC2311.JPG
  'https://lh3.googleusercontent.com/d/1orhmOqCG6SDidx76ymL630Nsc7_6TSRM',  // _DSC2313.JPG
  'https://lh3.googleusercontent.com/d/1KipVgLiIM-Z2joo0zoDWYzDd157bMzHh',  // _DSC2315.JPG
  'https://lh3.googleusercontent.com/d/1txg8BRocWaqmPz7zqeiKxGE6XGGRVnFz',  // _DSC2316.JPG
  'https://lh3.googleusercontent.com/d/1Qz1HLMzRSE00mlzBOKWelWbXGFt-K8a9',  // _DSC2317.JPG
  'https://lh3.googleusercontent.com/d/1LaJSR-Ca6KT8IEGxbFqks12I4KssEfr1',  // _DSC2318.JPG
  'https://lh3.googleusercontent.com/d/1QSNFR-eE1w23DgePvAUfmh4DeHWtH8lb',  // _DSC2319.JPG
  'https://lh3.googleusercontent.com/d/1QMeQHEG6WB2YOOAl6KGOeARJ1thE5UrH',  // _DSC2321.JPG
  'https://lh3.googleusercontent.com/d/15UBqRS6Jmx8gu30lym0lScuujdvFshx3',  // _DSC2322.JPG
  'https://lh3.googleusercontent.com/d/1RhfSfuiLbJ30aFHP2tzBAJtCn6a41DuV',  // _DSC2323.JPG
  'https://lh3.googleusercontent.com/d/1HEIHWhwT4wrG_iWk1nioArXDKVoUnRZ8',  // _DSC2330.JPG
  'https://lh3.googleusercontent.com/d/1yrMh438yIbKrAWLVaundGGd9ej4QXogY',  // _DSC2337.JPG
  'https://lh3.googleusercontent.com/d/1LnImLovfo9EquAn1Z8riG4wm--NwgFGO',  // _DSC2338.JPG
  'https://lh3.googleusercontent.com/d/1Uu-kZqC5p0juRJekw0YAiuz5b7nqXOK9',  // _DSC2339.JPG
  'https://lh3.googleusercontent.com/d/10DWtQHQdu2RH0kmUDifZlvtSLR42Kz5X',  // _DSC2341.JPG
  'https://lh3.googleusercontent.com/d/17IJ5JNb9jlKD23F0wsq421we9FGMmOaQ',  // _DSC2345.JPG
  'https://lh3.googleusercontent.com/d/18LR-r6HQRjozmH4ATmlYAeg9we4327uo',  // _DSC2347.JPG
  'https://lh3.googleusercontent.com/d/1rcLpmJX8G3EehY1pGiTb12hpV-L9PiOj',  // _DSC2348.JPG
  'https://lh3.googleusercontent.com/d/1AiWZ4AHmviMAlL6Csqe4zNCS5X4LhHNU',  // _DSC2350.JPG
  'https://lh3.googleusercontent.com/d/1tt9CjBuJncppKTPpXVvzcBvJSgaffIz7',  // _DSC2351.JPG
  'https://lh3.googleusercontent.com/d/1dS-EuzCNIOBkKOqVFkrEI0LnHIER583t',  // _DSC2352.JPG
  'https://lh3.googleusercontent.com/d/1-z9dWU_L9TdsyMo_041wKWpum3qN42sW',  // _DSC2353.JPG
  'https://lh3.googleusercontent.com/d/1qFvxNkV1FUYsOmOS2eGWF8wW-3X0TH4L',  // _DSC2354.JPG
  'https://lh3.googleusercontent.com/d/1m2dI5-1IA63S6i__H4xZZImshEevMjY1',  // _DSC2355.JPG
  'https://lh3.googleusercontent.com/d/1XQiH5SOFBhFUwR2Pxhx17W_GRkdKhOX4',  // _DSC2358.JPG
  'https://lh3.googleusercontent.com/d/1DEWgEpaO93rUaFEArhOUx6x3F84qDX-V',  // _DSC2360.JPG
  'https://lh3.googleusercontent.com/d/16LcoolnZQ9oW3ur3TAqdgbIV5Kn7vH3t',  // _DSC2361.JPG
  'https://lh3.googleusercontent.com/d/1gDaXgcS8YYGRk-579Xsg3S9mkiGhvbMw',  // _DSC2362.JPG
  'https://lh3.googleusercontent.com/d/17abR2CnDWWXp4wZTf-9_pCAhHGyujtrJ',  // _DSC2365.JPG
  'https://lh3.googleusercontent.com/d/1eTfJ814axRzFwb5GlATc9EU78Qei9wCp',  // _DSC2366.JPG
  'https://lh3.googleusercontent.com/d/1KFjlW-i6O0T7ESM1fArwXC8lD2khpPmO',  // _DSC2368.JPG
  'https://lh3.googleusercontent.com/d/13KvAaasopMIy6KFC90A2-qAprQVM8aj8',  // _DSC2370.JPG
  'https://lh3.googleusercontent.com/d/1zcIGXyrCbvhxcERiZFfFZ-hwiDWp-NKd',  // _DSC2372.JPG
  'https://lh3.googleusercontent.com/d/19A_wONIek_bORI_DlyEcS74NEiXuDf5_',  // _DSC2373.JPG
  'https://lh3.googleusercontent.com/d/1Wb_j2GDMQMBwZbK2HLcLMfGVYN4JCBvc',  // _DSC2374.JPG
  'https://lh3.googleusercontent.com/d/18OgXNS7eH7EXa5Ne9Wn00FhBvaGru1qY',  // _DSC2375.JPG
  'https://lh3.googleusercontent.com/d/1b7HlPKUqbiA8s7YWI3_XJ-zUL8InPJZG',  // _DSC2376.JPG
  'https://lh3.googleusercontent.com/d/1LdnfZ8qMfSApFzUR7C7Hax108osBjsqq',  // _DSC2377.JPG
  'https://lh3.googleusercontent.com/d/1GMeJyb_8_EKK3zCcyfDOpFaqriSglK9U',  // _DSC2378.JPG
  'https://lh3.googleusercontent.com/d/1gn68YSVMhTcGmkrGApS9Tt_EL9jvh1D2',  // _DSC2379.JPG
  'https://lh3.googleusercontent.com/d/1RfnwqhpAf911GtidmuhpIOKyKFOAnqKC',  // _DSC2380.JPG
  'https://lh3.googleusercontent.com/d/1HLxMxqHxjZFSkhzKgLdmUe_rNPnkZPwn',  // _DSC2385.JPG
  'https://lh3.googleusercontent.com/d/1kyZmH0nA361jrdZnJBigIBhi5867F0GK',  // _DSC2387.JPG
  'https://lh3.googleusercontent.com/d/1LBjtJKV-Aee7wGTWHaeJUQGqUw8aCijQ',  // _DSC2391.JPG
  'https://lh3.googleusercontent.com/d/1cPAEf4aEVUTKlAPkAcjxRS8kc0l_9GEm',  // _DSC2393.JPG
  'https://lh3.googleusercontent.com/d/15vtr_31ZbbGu436ZTr3GyCslVpilxSIK',  // _DSC2395.JPG
  'https://lh3.googleusercontent.com/d/1uBkUm7kPMS3Wh3AyJ9c2WTRV9OjXODJ_',  // _DSC2396.JPG
  'https://lh3.googleusercontent.com/d/1wje5efIP1V2etEtWVk9YgeJHIZaw-nvb',  // _DSC2397.JPG
  'https://lh3.googleusercontent.com/d/1pUkipQ5KoSEwwvJ03MC2AAxj8rkdoBsv',  // _DSC2398.JPG
  'https://lh3.googleusercontent.com/d/1a0lRZuz4auPCLvuFij8T29zhkJ2PCxEk',  // _DSC2401.JPG
  'https://lh3.googleusercontent.com/d/1EpxrhT8IIW-Eimhl5DIz7hRwfMZVxIKH',  // _DSC2402.JPG
  'https://lh3.googleusercontent.com/d/1D3YeHuqrzdFZ_EWIT5pUU-evVC8Zk1_H',  // _DSC2403.JPG
  'https://lh3.googleusercontent.com/d/1VvlvChUsvUmTzY8bRFpgb3jUSY0KEIfo',  // _DSC2405.JPG
  'https://lh3.googleusercontent.com/d/17aezZ605dNnL30YeevtTGYtQeEVtY31N',  // _DSC2406.JPG
  'https://lh3.googleusercontent.com/d/1H7NagKwKzV9ioJM6j-KYB-XLPRqCau-1',  // _DSC2409.JPG
  'https://lh3.googleusercontent.com/d/1LTuu2F8FEOqDuNqhTOCwB96xLQwJ1TyD',  // _DSC2410.JPG
  'https://lh3.googleusercontent.com/d/1C-niDkFf5t-Bur6w_hMkzwJYQoASdz3_',  // _DSC2412.JPG
  'https://lh3.googleusercontent.com/d/1rBDMr7kr3JebBXW61jv2HDLAWWVUBLJY',  // _DSC2413.JPG
  'https://lh3.googleusercontent.com/d/1ODb2aEx6y2f-c8W2bILaUjpv6ZkwwKR-',  // _DSC2414.JPG
  'https://lh3.googleusercontent.com/d/1rZC0aU1FLu9yK7dt2ImOiYY9-9RGCf-D',  // _DSC2415.JPG
  'https://lh3.googleusercontent.com/d/1kEi9lUvS6aQ07DqRS5W-MztcMhGGxG5l',  // _DSC2421.JPG
  'https://lh3.googleusercontent.com/d/1tzUnxa0a6TGJTMddOlYql1zNza0ix6fl',  // _DSC2422.JPG
  'https://lh3.googleusercontent.com/d/1MSIp9UjjY8G4L6zi_uXsi6yQ3wqTMcph',  // _DSC2423.JPG
  'https://lh3.googleusercontent.com/d/1UIm9CEPsDvZO8WhpFT68ARwryEcTpRYm',  // _DSC2424.JPG
  'https://lh3.googleusercontent.com/d/1b_16Hw8nzz6_BgOWqA2yiYT8tDJAJZBD',  // _DSC2425.JPG
  'https://lh3.googleusercontent.com/d/1U5navyL-OoddjTFyMiKdQHgZyUe47Azt',  // _DSC2427.JPG
  'https://lh3.googleusercontent.com/d/1wxNzwvwWUTtIVB-X8CCShLKKUXNBfTGf',  // _DSC2428.JPG
  'https://lh3.googleusercontent.com/d/1lnv8Cw09zemV8wJb77SxEXq2C4UHC17Z',  // _DSC2429.JPG
  'https://lh3.googleusercontent.com/d/1efEslH6X8pWMsc6CE2ZLPn94Wo2edVr0',  // _DSC2430.JPG
  'https://lh3.googleusercontent.com/d/1yqnC0PqTuHosJjuzxMJLdbXuJaGUJXKM',  // _DSC2431.JPG
  'https://lh3.googleusercontent.com/d/1qrEMuevopUHcLvlsTKosOJ3oxhcNAAwY',  // _DSC2432.JPG
  'https://lh3.googleusercontent.com/d/1wSzftysb79sE9DDrNc8QD7jn8Kaop_Ak',  // _DSC2433.JPG
  'https://lh3.googleusercontent.com/d/1-tiCKKXM6-wuTOUv0k1YMQTSi8lWZz7Y',  // _DSC2434.JPG
  'https://lh3.googleusercontent.com/d/1j4FfOvWRVjkarfRPCerWCNyaHhkvU2A7',  // _DSC2435.JPG
  'https://lh3.googleusercontent.com/d/1p8YE-bQMr53zHe_a4JOG1kpS3N0u1z1i',  // _DSC2436.JPG
  'https://lh3.googleusercontent.com/d/1VrLpfXBlteJyHqvj-yiYnQw6DGXobkCj',  // _DSC2437.JPG
  'https://lh3.googleusercontent.com/d/1riH1NK10DqnMa0Nu_IgpPWkX2SAjuxjB',  // _DSC2438.JPG
  'https://lh3.googleusercontent.com/d/1iiQVJ9cK1f4r1kNXiTD0BNFVRNn3bpnL',  // _DSC2451.JPG
  'https://lh3.googleusercontent.com/d/1WQ2u3BTNzHXqFGk9rfBFbX7L3WiXGJmj',  // _DSC2452.JPG
  'https://lh3.googleusercontent.com/d/1f7FPv5XV2joEPblEmnUYWc0Z_2yJWO5u',  // _DSC2455.JPG
  'https://lh3.googleusercontent.com/d/1hjkYolrYPCZ_4ff8ImuGZtvHizxCoBe0',  // _DSC2457.JPG
  'https://lh3.googleusercontent.com/d/1icnT5PPxeOGVdP1uhHkgPs-aDbEyB1Ey',  // _DSC2458.JPG
  'https://lh3.googleusercontent.com/d/1wvMSw-n03gtdzeqetge73grl-CTbjG0L',  // _DSC2459.JPG
  'https://lh3.googleusercontent.com/d/1SufZ6GmzN8xDbRgwJs8jK00mt7VaUn2A',  // _DSC2460.JPG
  'https://lh3.googleusercontent.com/d/1M7xpPKSIj3_WZAe9m8Ed8Cud3Daq5GQ8',  // _DSC2461.JPG
  'https://lh3.googleusercontent.com/d/1jd2fZuyTyUAIZbmJ_HoZmiD8F9fZgALZ',  // _DSC2463.JPG
  'https://lh3.googleusercontent.com/d/1--Y-CgKvJomSnzPg8-2pUuVJpQkIuK-5',  // _DSC2464.JPG
  'https://lh3.googleusercontent.com/d/1S6Pt6NbYeWgXD_uQWa792-yiFfWPmOZe',  // _DSC2465.JPG
  'https://lh3.googleusercontent.com/d/10966uyLUhApz1tZBDaSe3GfQRkwjdJzn',  // _DSC2467.JPG
  'https://lh3.googleusercontent.com/d/14JE_SGkkD30WJ3r2nSQJAvPq_1QOnNfd',  // _DSC2468.JPG
  'https://lh3.googleusercontent.com/d/1mwv1djbUCJR2e9emLUCLDVBY_0b4PXGN',  // _DSC2469.JPG
  'https://lh3.googleusercontent.com/d/1f9kDVM7EtTO4OV-gGeP6Rax2xp-MrGgo',  // _DSC2470.JPG
  'https://lh3.googleusercontent.com/d/1u8RbcUIq7nuZ9MAYzrq4BGV51k0CIT-k',  // _DSC2471.JPG
  'https://lh3.googleusercontent.com/d/1qyurA1oqV3KcnBWalBW2dkNmrXsfQBN1',  // _DSC2474.JPG
  'https://lh3.googleusercontent.com/d/1hlMwdh7OQrT7h7pT5FaliW1Lg3KHCGXF',  // _DSC2477.JPG
  'https://lh3.googleusercontent.com/d/1ACnH4WqfMWu7yydfwJM3f7hK_rK5l2iG',  // _DSC2478.JPG
  'https://lh3.googleusercontent.com/d/10aNXTBnY2ETW1y8DUh_50-rOgl-2RqDc',  // _DSC2479.JPG
  'https://lh3.googleusercontent.com/d/1ZL0R_dT8Vq6kJAamBFREuzSDo6zx5mkV',  // _DSC2481.JPG
  'https://lh3.googleusercontent.com/d/1-v_ltUdWRn0ZTfuybeppRlFH8JHVgCoI',  // _DSC2483.JPG
  'https://lh3.googleusercontent.com/d/1UIdjYfGrbPF32UykD576xEYhvEShJ35F',  // _DSC2484.JPG
  'https://lh3.googleusercontent.com/d/1BXMhp3kHrwhD-6tLGJ0k-hP-8KXWGkYo',  // _DSC2486.JPG
  'https://lh3.googleusercontent.com/d/1w2kbhSd4U4it80AZABzKps5gnziZQsWZ',  // _DSC2487.JPG
  'https://lh3.googleusercontent.com/d/1u85mRjR8v1JhD3vaIQS6uf4Lcf9_11No',  // _DSC2488.JPG
  'https://lh3.googleusercontent.com/d/1z90u2hYUjYmfVEyvee00LKSF-4Nk21Gk',  // _DSC2491.JPG
  'https://lh3.googleusercontent.com/d/1nZcnMC2DVJJFSkQid0neLM23ezje4biV',  // _DSC2492.JPG
  'https://lh3.googleusercontent.com/d/142kMG3QO_kAJ127SRDVjmWXKJyV9ARrM',  // _DSC2493.JPG
  'https://lh3.googleusercontent.com/d/1D6Q_AenPpDciBXaEr-FzlEAOxeCR5VxW',  // _DSC2496.JPG
  'https://lh3.googleusercontent.com/d/1q6-PABYwhAZMhwit6kboO1CxXmec_iTf',  // _DSC2498.JPG
  'https://lh3.googleusercontent.com/d/19AFiBAy8cwoxyWF2-yB4fsbM53VNJfbd',  // _DSC2499.JPG
  'https://lh3.googleusercontent.com/d/1kvvk0H4fU0J5rTwlkroEif9GMX_apr0i',  // _DSC2500.JPG
  'https://lh3.googleusercontent.com/d/1z31vWTYkheBdq04H7qqdxtwL5YCj-PIZ',  // _DSC2502.JPG
  'https://lh3.googleusercontent.com/d/1Ll-6b_VexccZS7fZJH9S7HXrb3eFjGhf',  // _DSC2503.JPG
  'https://lh3.googleusercontent.com/d/1npe5_CiZ87h4NtcJwFF1jmgLhU_DvDR_',  // _DSC2504.JPG
  'https://lh3.googleusercontent.com/d/1RB3dhyel-W-x3u4wn6xnKbYRM9AYlL_M',  // _DSC2505.JPG
  'https://lh3.googleusercontent.com/d/16vDpx1q3gmE3hnvS-5kSaUl9BL34tE86',  // _DSC2507.JPG
  'https://lh3.googleusercontent.com/d/1auYU7uBBzI4G_d4gmn-rfUz5XwoddRC-',  // _DSC2508.JPG
  'https://lh3.googleusercontent.com/d/16wx81EJBYxON02r3k5oRyY3-v-9BMfrv',  // _DSC2510.JPG
  'https://lh3.googleusercontent.com/d/1yL5nXkBYsAKV7RDrKytrs0rU_FJXJ9G9',  // _DSC2511.JPG
  'https://lh3.googleusercontent.com/d/1eFei9yBJuMsL_RMYvbAeJ-fX4aypcXV9',  // _DSC2512.JPG
  'https://lh3.googleusercontent.com/d/1oeWtFkrf10HqINJFydsRgkUfTg_OtFxH',  // _DSC2513.JPG
  'https://lh3.googleusercontent.com/d/1Z2uwcUVT7VkhXbV0SM_AvRW2N-QRfChO',  // _DSC2515.JPG
  'https://lh3.googleusercontent.com/d/1r8PlcBeXmIJ3EowVUU6c2W5Xoc64-yXR',  // _DSC2516.JPG
  'https://lh3.googleusercontent.com/d/19SwfXl2hMIGi0R-GJFZ9TaJfcLI8wDwx',  // _DSC2518.JPG
  'https://lh3.googleusercontent.com/d/1YB_X4-8OkvxHnq5cvv3tjMmn8tWP1xfF',  // _DSC2521.JPG
  'https://lh3.googleusercontent.com/d/1HtdAEjLuSJQscgk-GD47SgH9-YVbeQDn',  // _DSC2524.JPG
  'https://lh3.googleusercontent.com/d/1QSU0e0WH5PVyS9jk-xDrRbcfZVJthuVd',  // _DSC2525.JPG
  'https://lh3.googleusercontent.com/d/1ZDei6METgJMXcDISyeIQxjeCkyYRaId4',  // _DSC2528.JPG
  'https://lh3.googleusercontent.com/d/1vxhd3me0pHuq2b34_3wgknbH4yy11WH9',  // _DSC2530.JPG
  'https://lh3.googleusercontent.com/d/1Wd56CQgZTXaUF1a-eVbCk-EvrwJXw34y',  // _DSC2531.JPG
  'https://lh3.googleusercontent.com/d/186LHWCR4V2cPcR1xwNYPcW7akVsLm_Up',  // _DSC2534.JPG
  'https://lh3.googleusercontent.com/d/1QzmPoVXrsvaQvuQtygUe05dQ4tu5ZyNR',  // _DSC2535.JPG
  'https://lh3.googleusercontent.com/d/1kzCyx3-drwhFL7PX8h9owH9Rt6X-9Xha',  // _DSC2537.JPG
  'https://lh3.googleusercontent.com/d/1NKnETDnD7zFKQqtRc8hrNoyspU4NW2A4',  // _DSC2539.JPG
  'https://lh3.googleusercontent.com/d/1lEtX9tBEUwWJ_amhP51Yf4hS5fQBAfUe',  // _DSC2541.JPG
  'https://lh3.googleusercontent.com/d/1W4EFFQGb8Os7vOuunfwmhpMHaR5MVsEo',  // _DSC2543.JPG
  'https://lh3.googleusercontent.com/d/19D1jyAB0Z3Jsx87jLlqFbAy9uf2mUT0V',  // _DSC2544.JPG
  'https://lh3.googleusercontent.com/d/1GfDeFGa4w3KKWxFdnDSl_3zkPUu_iPFH',  // _DSC2545.JPG
  'https://lh3.googleusercontent.com/d/1vJmisefp3YjlLvSrpbMWkAouLOeEa91O',  // _DSC2546.JPG
  'https://lh3.googleusercontent.com/d/1TOnzYz1MvLJdQbpztpMSVAkS1PWFgNiy',  // _DSC2548.JPG
  'https://lh3.googleusercontent.com/d/1Bwuo_WB1jHhQad2w8KX3S-maPRWXlfM6',  // _DSC2549.JPG
  'https://lh3.googleusercontent.com/d/1ViFEMGmRnvCOVb6WqgVidH9qy45i4slM',  // _DSC2550.JPG
  'https://lh3.googleusercontent.com/d/10_vlIiN4D6U6GejZel0JOGLjcEaUe95V',  // _DSC2551.JPG
  'https://lh3.googleusercontent.com/d/1OmqsUw7uAEZ-ayhBjsF3l_IZ9Bm_Pska',  // _DSC2552.JPG
  'https://lh3.googleusercontent.com/d/1lYLBXYao1JyY7LWKzUCTo6PPzqs5wN27',  // _DSC2553.JPG
  'https://lh3.googleusercontent.com/d/1VyvjSIEIzHlFZ-YVbHseSD53Qzy9Y7Ln',  // _DSC2554.JPG
  'https://lh3.googleusercontent.com/d/1aOGvo0WeYIJBiUjKC21ma4btTL922EBc',  // _DSC2556.JPG
  'https://lh3.googleusercontent.com/d/1Sd_25yZ-GeuDnDAs_vlqivWm_HsHOUhB',  // _DSC2558.JPG
  'https://lh3.googleusercontent.com/d/1k4CpPuj6gmSTasIXzDiMlVfSxOOrb4iy',  // _DSC2559.JPG
  'https://lh3.googleusercontent.com/d/1BDjjOsbmSU6qwfZYySDTaEEIH0dEL3gD',  // _DSC2561.JPG
  'https://lh3.googleusercontent.com/d/1xGSw-RbvcQIX6cA9sFXtrLjYPxKRnDzu',  // _DSC2562.JPG
  'https://lh3.googleusercontent.com/d/1CH2gmTXj_HKnpXoTeomUO75mhVxfSPyN',  // _DSC2563.JPG
  'https://lh3.googleusercontent.com/d/1FoletN9FwVzU8iLaGWVJ_YZD_-duaWTy',  // _DSC2564.JPG
  'https://lh3.googleusercontent.com/d/1CH5yBQqGxADbsBUBxSS4CHjtmBjxb9ok',  // _DSC2565.JPG
  'https://lh3.googleusercontent.com/d/16WQaPhLD4t5UYOn54sjQQ6R_AFBwsXto',  // _DSC2566.JPG
  'https://lh3.googleusercontent.com/d/1JXrE5FxNOiKgkloOqK2-lZiIQ5gCSX0m',  // _DSC2567.JPG
  'https://lh3.googleusercontent.com/d/1Sal5pvHQLqGB7QpuTeTXwfzqJoZBtQmv',  // _DSC2568.JPG
  'https://lh3.googleusercontent.com/d/1Z3ktSPQRkM3WIUN2UXdzInVsdN0aDpM8',  // _DSC2569.JPG
  'https://lh3.googleusercontent.com/d/1uQG2KGFRZVv-PfHO-ddjT0UDYGWIHrSy',  // _DSC2570.JPG
  'https://lh3.googleusercontent.com/d/1CxXOarLUL-Vik7dKrC0aLTszH8lOK6iN',  // _DSC2571.JPG
  'https://lh3.googleusercontent.com/d/1JW74cIG5KSRIz_SEw0caxyAkR_H-ASY9',  // _DSC2572.JPG
  'https://lh3.googleusercontent.com/d/1Ws9MJ8FSHKDHcs_At-UxKHZDCh4m8cAh',  // _DSC2573.JPG
  'https://lh3.googleusercontent.com/d/1irWJHAyLa0xosbLiAXqgT5_oiEVaz7xn',  // _DSC2574.JPG
  'https://lh3.googleusercontent.com/d/1Q3GvMT3LIuFMNMvjIhuO3jf3qKFXlJo2',  // _DSC2575.JPG
  'https://lh3.googleusercontent.com/d/1F8Ie8RkF1t1eRd2QbBgsQDIlyliq58tQ',  // _DSC2576.JPG
  'https://lh3.googleusercontent.com/d/1dstYv3q00pbddcnrPx3fHc6PohYZtz_u',  // _DSC2577.JPG
  'https://lh3.googleusercontent.com/d/1acMreqtm76uK4cD1MVyjt2tAOr1rUHyG',  // _DSC2578.JPG
  'https://lh3.googleusercontent.com/d/1hdbXWMyIlolyRO5M72vZvRWYoCQgcr0x',  // _DSC2579.JPG
  'https://lh3.googleusercontent.com/d/1Y1uU3afHQvE02mk35ydGi3mLaBCyrvve',  // _DSC2582.JPG
  'https://lh3.googleusercontent.com/d/15d0qUqJlL7__PFbRNKZVr7HCMOAONhtZ',  // _DSC2583.JPG
  'https://lh3.googleusercontent.com/d/146HRXRG8mjQzhPfXZlC9sPN2N3meVK-Y',  // _DSC2584.JPG
  'https://lh3.googleusercontent.com/d/1nN8LgVvNposAUQKuPjTSIKNH12js2Yfw',  // _DSC2585.JPG
  'https://lh3.googleusercontent.com/d/1ZjeDkD_wzUvBmLip_QdMw9LHfDekowcf',  // _DSC2586.JPG
  'https://lh3.googleusercontent.com/d/1f2dpl4hMjHdmQHZ7Z_dCgkyZjm61YMhd',  // _DSC2587.JPG
  'https://lh3.googleusercontent.com/d/1gT9ZnkQnT75DK67dFJWywwNFdanpE15c',  // _DSC2588.JPG
  'https://lh3.googleusercontent.com/d/1c3XQMULK-Rorqf9zLRhGcQl48YwRv9SO',  // _DSC2589.JPG
  'https://lh3.googleusercontent.com/d/1uVRl720E11gcgmcbG0_FtZd1pxZ0JhRy',  // _DSC2590.JPG
  'https://lh3.googleusercontent.com/d/1cWefscsii44Ou_YN0kS_PZhIroUBeAYp',  // _DSC2591.JPG
  'https://lh3.googleusercontent.com/d/11srXOqyPc4bq0kIoEXy1nBZWrr-teQ26',  // _DSC2592.JPG
  'https://lh3.googleusercontent.com/d/1Wuz4jSR3bgnaf-bN4Ot0lhmLYRomq5n-',  // _DSC2593.JPG
  'https://lh3.googleusercontent.com/d/1mAsD1AtgFTcv071w4JrjoIkCk86Tg1eU',  // _DSC2594.JPG
  'https://lh3.googleusercontent.com/d/1LC9SUmPWSVdyFnzBuiv8JTZKuggtBZWo',  // _DSC2595.JPG
  'https://lh3.googleusercontent.com/d/13E4U2LEzrB2ECohfzS1Qr3_jVlKqF_ih',  // _DSC2596.JPG
  'https://lh3.googleusercontent.com/d/1jTRzHQ9Zc96GucK0y9dHXGCKmY6CYSOo',  // _DSC2597.JPG
  'https://lh3.googleusercontent.com/d/1IY4e6cUIHlLvLxtQ-9ukUB67Ldnp-pR3',  // _DSC2598.JPG
  'https://lh3.googleusercontent.com/d/1ij4zWmDjUTiNAiUD9epJOTKXyDoJPXy0',  // _DSC2599.JPG
  'https://lh3.googleusercontent.com/d/1oSEGDEF2Q8IfcPdW77i30vXBA53dn0Pi',  // _DSC2600.JPG
  'https://lh3.googleusercontent.com/d/1dmMDdencnEe9sfgxH60fRL-ICeJO9JxQ',  // _DSC2601.JPG
  'https://lh3.googleusercontent.com/d/1z_8_C82FRqdXNTKugm9t55mBQ-R2pxLV',  // _DSC2602.JPG
  'https://lh3.googleusercontent.com/d/1JmNCDVjFA94rL8OgzxVmnJ0GJuQLV5Hz',  // _DSC2603.JPG
  'https://lh3.googleusercontent.com/d/14bSAAWGHclD0cJEiFRZl5Frrg7r6m1QN',  // _DSC2604.JPG
  'https://lh3.googleusercontent.com/d/1foT-5_ADUrsVF7pWlq-vj4Q6ullUFFry',  // _DSC2605.JPG
  'https://lh3.googleusercontent.com/d/1uFndD-FPfrRTxvvzmEF4AKFNj3kTjkTm',  // _DSC2606.JPG
  'https://lh3.googleusercontent.com/d/1I_9sJnKziWFVsPU_zRsm93GZXveErh98',  // _DSC2607.JPG
  'https://lh3.googleusercontent.com/d/1T5WIi5H3rqnInmX5r1qVYJCmuqFUwWq8',  // _DSC2609.JPG
  'https://lh3.googleusercontent.com/d/1t1jJKwMKl3kq-YOud_ltuAtV2wLIpbFP',  // _DSC2610.JPG
  'https://lh3.googleusercontent.com/d/1ixs04-sD9MVlZxS8l4x6A668PStEvqNP',  // _DSC2611.JPG
  'https://lh3.googleusercontent.com/d/13pQMBi5n-cH7lgEKzlrNKqwJva1feonP',  // _DSC2614.JPG
  'https://lh3.googleusercontent.com/d/1UEHcPVCTLYt3JKMhqdkeQqCBGmN6_uc7',  // _DSC2616.JPG
  'https://lh3.googleusercontent.com/d/13Ah6SArzWhBzIGxUatxTIW-vTRvABQ63',  // _DSC2617.JPG
  'https://lh3.googleusercontent.com/d/1-2FsJvH_79x3Pk8d_aXMSmbIzCck_x1S',  // _DSC2618.JPG
  'https://lh3.googleusercontent.com/d/1gJW1hY8l0Tz_Uwe3MMOj7ZsvJ3a4qzlH',  // _DSC2620.JPG
  'https://lh3.googleusercontent.com/d/1FzGrKJM3FggB52mghZ6tWgekIrmzSDo_',  // _DSC2622.JPG
  'https://lh3.googleusercontent.com/d/1TWZNKMyRPEfZq-iJTstHfW9lRrP3U5OX',  // _DSC2623.JPG
  'https://lh3.googleusercontent.com/d/1w_IGWTzpjO8equfz6_QJdTJCs2TmIGPV',  // _DSC2625.JPG
  'https://lh3.googleusercontent.com/d/1Su9V9vzgWceHcG3quhitgeGjNOiRbxFV',  // _DSC2626.JPG
  'https://lh3.googleusercontent.com/d/1xZbOeypId2LihST1fI8u8qP4tFC1PC3W',  // _DSC2627.JPG
  'https://lh3.googleusercontent.com/d/1O7eS8KkwWisHncxKX0PF6PowwKgGjx_g',  // _DSC2629.JPG
  'https://lh3.googleusercontent.com/d/18rW2ZdEjARk-TXqoMrXm7TN6RFn0sLeT',  // _DSC2630.JPG
  'https://lh3.googleusercontent.com/d/1yGv3Pr5tOd8t_2SSFAG4k-Kwm0f50yuT',  // _DSC2631.JPG
  'https://lh3.googleusercontent.com/d/1F7ZAdpK1HYKJ9NEIiPgPsyGm-WYTbqkA',  // _DSC2632.JPG
  'https://lh3.googleusercontent.com/d/1GuLnhnlp5lEkvW9pG1o0j8c3w3-I_rSF',  // _DSC2634.JPG
  'https://lh3.googleusercontent.com/d/1x3tqPlY5uwD2LkJfu7sz4ilgTp1k_YYF',  // _DSC2635.JPG
  'https://lh3.googleusercontent.com/d/1Ex3DB3dn9RtjDhdMdPaaxAc_8hFC2uM4',  // _DSC2637.JPG
  'https://lh3.googleusercontent.com/d/1mZzbA9v-COAp920X0dx-v1at4SdR_NGC',  // _DSC2638.JPG
  'https://lh3.googleusercontent.com/d/18XU6FTj-7TSUxwO5qKUXuE0vNuUljtbW',  // _DSC2639.JPG
  'https://lh3.googleusercontent.com/d/15qQ7fZEDewnzYcmoBYOKP01D3SazizwM',  // _DSC2640.JPG
  'https://lh3.googleusercontent.com/d/1xVaBc567a3JKXW5EU84DlDKM0z9mvbH-',  // _DSC2641.JPG
  'https://lh3.googleusercontent.com/d/1T6al77qH0sKxuBgivLNy2uIHDXwsksas',  // _DSC2642.JPG
  'https://lh3.googleusercontent.com/d/1GEyN3a_C-Oq5jcPhmLprF0GGECsGlJu7',  // _DSC2643.JPG
  'https://lh3.googleusercontent.com/d/1m63y_ZQlRj85KRSVE1vXJhFpE7j8CUji',  // _DSC2644.JPG
  'https://lh3.googleusercontent.com/d/1iexGA6CrpUCaQY_r8KhLaRqiVprdtQ5S',  // _DSC2648.JPG
  'https://lh3.googleusercontent.com/d/1I1lvjt02GuKZ8gQRlwa2bmc6X98HniQs',  // _DSC2649.JPG
  'https://lh3.googleusercontent.com/d/1T7sH5HadK9Qs2oths8NEftNWiJA0CNjA',  // _DSC2650.JPG
  'https://lh3.googleusercontent.com/d/144y--nHHUQSa-RksxWb0nClL89XerwDu',  // _DSC2651.JPG
  'https://lh3.googleusercontent.com/d/1D5LgfetGbvSg8zKA774vxcWmUItOuSRD',  // _DSC2656.JPG
  'https://lh3.googleusercontent.com/d/10Rlo4mJq4dVLYe9TNZZ8NQan2o0gt8NE',  // _DSC2657.JPG
  'https://lh3.googleusercontent.com/d/1dDvkZ4i7UXbogLoDldURV00c4kAjhqKp',  // _DSC2659.JPG
  'https://lh3.googleusercontent.com/d/1kPNXE3tOJZDC_iTt2cZqd9cPHh9NBa7l',  // _DSC2660.JPG
  'https://lh3.googleusercontent.com/d/1zZRT_xshy-uA-AwIKz7KKy3eDtF_9dwX',  // _DSC2661.JPG
  'https://lh3.googleusercontent.com/d/1MSfa0ulnru_enjcgG24XvdxD6xqKf3lX',  // _DSC2663.JPG
  'https://lh3.googleusercontent.com/d/1MFfqus0pxwHiSWa5qd_txCUwEuGRHkB3',  // _DSC2664.JPG
  'https://lh3.googleusercontent.com/d/116cwcTHJgmp50wj4QWKZ7gmQ-tPPxIeu',  // _DSC2665.JPG
  'https://lh3.googleusercontent.com/d/1CrCPeBuC2DYrs2F7HZm6-tL5g6TQRLVg',  // _DSC2666.JPG
  'https://lh3.googleusercontent.com/d/1RvFzua3-N-jF2jjk2KLT9z9MwS21s7hj',  // _DSC2667.JPG
  'https://lh3.googleusercontent.com/d/1E9nmQeeEeCETqCVglXreyTRl9z4Z1LfZ',  // _DSC2668.JPG
  'https://lh3.googleusercontent.com/d/1CqaHxaJ-P43ITtPpycA2aqUXYkMtS6aG',  // _DSC2669.JPG
  'https://lh3.googleusercontent.com/d/1RWL_MxTrzcWuohMwuNw36_9sshZDXuqj',  // _DSC2670.JPG
  'https://lh3.googleusercontent.com/d/1xhO_5DYkevVKBqJNfCyGY-bpFC7o4bXq',  // _DSC2672.JPG
  'https://lh3.googleusercontent.com/d/11RLIw2vbASUAKeNk5VXtNGYBPJqv8Gr9',  // _DSC2674.JPG
  'https://lh3.googleusercontent.com/d/19IgJFsN7fgXZr90-Z_ZgM0Rtpw1eOhIn',  // _DSC2675.JPG
  'https://lh3.googleusercontent.com/d/1umtykb7U9nsOZnzhwGVcbNLShOE36DiU',  // _DSC2678.JPG
  'https://lh3.googleusercontent.com/d/1MO2gAQ1L1f31CLFsvcURSpPsOa9MIAk3',  // _DSC2679.JPG
  'https://lh3.googleusercontent.com/d/1C2X-7wEav24-HnVormfRk_QGCAtmna4p',  // _DSC2680.JPG
  'https://lh3.googleusercontent.com/d/1AVwgNt9zCVRmIN-Y1OX6OvfYKSu8onBQ',  // _DSC2683.JPG
  'https://lh3.googleusercontent.com/d/1OQ9sOO14rf0nammzCbKYuwvCMmwgQxu6',  // _DSC2684.JPG
  'https://lh3.googleusercontent.com/d/1wgAN3-fVJoQw070vRoOOj5GkeZSTIPEn',  // _DSC2685.JPG
  'https://lh3.googleusercontent.com/d/1cV79KKJxdn4vVu0vv7kyD4oTz83RWJbK',  // _DSC2687.JPG
  'https://lh3.googleusercontent.com/d/1mDLVnUyn8B9DOANqf8P2fX2spHNqOWRR',  // _DSC2688.JPG
  'https://lh3.googleusercontent.com/d/1ues6HkJrNTMNcfWhatuPsfWFlhw2-8eE',  // _DSC2689.JPG
  'https://lh3.googleusercontent.com/d/1nchyhBPc2j0kg-XkUym0X3SmQgbLII6d',  // _DSC2690.JPG
  'https://lh3.googleusercontent.com/d/1IKkjox14CtHSpHTI_h2IX7fTccaFSo_h',  // _DSC2691.JPG
  'https://lh3.googleusercontent.com/d/1PdGfkY1e5-PjViiQRz_Pap_YLS-M3Oqn',  // _DSC2692.JPG
  'https://lh3.googleusercontent.com/d/11pRFwCUpCy8tUZ5Zu_DCd8zahtBPCbMr',  // _DSC2693.JPG
  'https://lh3.googleusercontent.com/d/1lFjLh7dfc7MwxqNXpzD59n953kvH3GrA',  // _DSC2695.JPG
  'https://lh3.googleusercontent.com/d/1rzX2z6w2p8ahm_yiisGIUwklY9QFYS4l',  // _DSC2696.JPG
  'https://lh3.googleusercontent.com/d/196rd6YAp9510SnQQ80-iL_TVrZ9JKV9h',  // _DSC2697.JPG
  'https://lh3.googleusercontent.com/d/16KXHfe7tqAJIKXfPjKHhXq3Z1tqulu9J',  // _DSC2698.JPG
  'https://lh3.googleusercontent.com/d/15aIyEX81ARByr2dPI_rKIQ4q9CZLzPS2',  // _DSC2699.JPG
  'https://lh3.googleusercontent.com/d/1fAVZFI0jRy33vGOvyQGGkfxINQDZ_FuA',  // _DSC2701.JPG
  'https://lh3.googleusercontent.com/d/1ZLn05-ETGz7IAlYIwm0ovk6nqHU0llEZ',  // _DSC2705.JPG
  'https://lh3.googleusercontent.com/d/1YYPWzLQWTcjHmy28w1vzfH8alk0xnSLZ',  // _DSC2706.JPG
  'https://lh3.googleusercontent.com/d/1vd3mR51x6C5l7j7fTvBH1B9SxD_b-q1P',  // _DSC2707.JPG
  'https://lh3.googleusercontent.com/d/1RE8a9nhalLYRQ0-qRl6g_D9zYi4pJZdA',  // _DSC2708.JPG
  'https://lh3.googleusercontent.com/d/1Bdr7GIUYFQx022BFE56cyJQuVo59G5si',  // _DSC2709.JPG
  'https://lh3.googleusercontent.com/d/1vsZRFym-sPlEcqeSvM9ajJRYj95zZ_GD',  // _DSC2710.JPG
  'https://lh3.googleusercontent.com/d/1t_hxL_xnGBSvzyKXtLpOFhkpW9gtpotl',  // _DSC2712.JPG
  'https://lh3.googleusercontent.com/d/1J46DK5tryJyt2mRa897Zhya55zYwN0pD',  // _DSC2713.JPG
  'https://lh3.googleusercontent.com/d/1gPF7r3cb3jXn3jOZbJBhVSytZK8P_QQ0',  // _DSC2715.JPG
  'https://lh3.googleusercontent.com/d/1PncQo_WXiqnkRHWygkaIUW6P4JByqGJI',  // _DSC2716.JPG
  'https://lh3.googleusercontent.com/d/1YzumQH1XJ79AwWeWbdbDPcHv-R4fX-XR',  // _DSC2717.JPG
  'https://lh3.googleusercontent.com/d/1DeLgLorwmHqAkyeaw9LGnKIffz6i8xZw',  // _DSC2721.JPG
  'https://lh3.googleusercontent.com/d/1ziY-_iElnl38Gn89_K-pzOjTn3o7LmW6',  // _DSC2722.JPG
  'https://lh3.googleusercontent.com/d/1vxCkecXCeSiRxOJty6RScv-0nXo97qxH',  // _DSC2724.JPG
  'https://lh3.googleusercontent.com/d/1g-3aSly8wywrra02l1SIJ1UY8yMl2d32',  // _DSC2725.JPG
  'https://lh3.googleusercontent.com/d/178sdke3wEqXr5l15DSJK3efaxTkWQQlH',  // _DSC2727.JPG
  'https://lh3.googleusercontent.com/d/1ZjCYiC1hBmP9CCP266caVwwHg3LEG9vA',  // _DSC2728.JPG
  'https://lh3.googleusercontent.com/d/1_lfI1S_e-SqZ-wfp45PFIHDOrRoPdaJc',  // _DSC2730.JPG
  'https://lh3.googleusercontent.com/d/1SHNPngNFYVthm9kI8bf1C0b3-flJWL-l',  // _DSC2734.JPG
  'https://lh3.googleusercontent.com/d/1Ws5Z3IZ5EX81ftAPlfaxKiCUoACuHbha',  // _DSC2737.JPG
  'https://lh3.googleusercontent.com/d/1ndXmxoUt3T2KMmC89fQ7IMxhRktFV_7L',  // _DSC2738.JPG
  'https://lh3.googleusercontent.com/d/1LJ8bEe9zr2w94mrO_4-YKlMqNZexknlY',  // _DSC2740.JPG
  'https://lh3.googleusercontent.com/d/1gSlgjizn-4T8qlVr6SxIOKoxBUrhYXyB',  // _DSC2741.JPG
  'https://lh3.googleusercontent.com/d/1Y_RvToplHXJrQGPHt3hngORvxGJ9HeSf',  // _DSC2742.JPG
  'https://lh3.googleusercontent.com/d/10bXwthqqnbBih7MJKKmynFlh8dpfblYj',  // _DSC2743.JPG
  'https://lh3.googleusercontent.com/d/1ds6EzjF4oI-fKnTg7gEHNhCyGpv2dvnQ',  // _DSC2745.JPG
  'https://lh3.googleusercontent.com/d/1LUZE_0U1st4IufHhoRRLFaVGN4ZEmcaK',  // _DSC2747.JPG
  'https://lh3.googleusercontent.com/d/1Y9PpVDQjjcPMX_6olWEehdr-nVBG5qLg',  // _DSC2748.JPG
  'https://lh3.googleusercontent.com/d/1NzpIO6Ajs3mA3Ij0hBIvIN0Wb7XCDHIB',  // _DSC2749.JPG
  'https://lh3.googleusercontent.com/d/1iNb0qQFFohQuSKK5xuza3WCxPuywD_ow',  // _DSC2750.JPG
  'https://lh3.googleusercontent.com/d/1_OxajQlx6AnDRL9H6N21LVDYZve8x2JJ',  // _DSC2752.JPG
  'https://lh3.googleusercontent.com/d/1Vt2uJ1WW7rh5T16SjucFMkBoyKAfjz6Z',  // _DSC2753.JPG
  'https://lh3.googleusercontent.com/d/1fO9uXU4sH20fldpQ8FNdNM0punW0R2Y0',  // _DSC2754.JPG
  'https://lh3.googleusercontent.com/d/1fxGfGycsg_op2tkXXSxrJzqwYUWzcIUI',  // _DSC2755.JPG
  'https://lh3.googleusercontent.com/d/14ddWjMUrrNUl78IM7BeiFic7A58031bh',  // _DSC2756.JPG
  'https://lh3.googleusercontent.com/d/1vgQo_b0mB1sbe0V3sUCfBTV3GTXuQCxj',  // _DSC2757.JPG
  'https://lh3.googleusercontent.com/d/1nUveAIguoBJiD9TtKsMdENT9pXiDY3_w',  // _DSC2759.JPG
  'https://lh3.googleusercontent.com/d/1nmGI9yZdYVwjyY2jRZ3xzyww1EQ98fLs',  // _DSC2760.JPG
  'https://lh3.googleusercontent.com/d/1J99Ewro42MjH1bHr08pQvhIXWMb32Btb',  // _DSC2762.JPG
  'https://lh3.googleusercontent.com/d/1rsQfJVBFuVF_GX3dMubJh4MRlkDaVLJa',  // _DSC2763.JPG
  'https://lh3.googleusercontent.com/d/1R38TYjlPAuH3iGn2PyCwtZzEh0ROQ6UK',  // _DSC2764.JPG
  'https://lh3.googleusercontent.com/d/1IGkpPbJsgO4lAmK9QQilexKSL8wkZu2o',  // _DSC2766.JPG
  'https://lh3.googleusercontent.com/d/1uW0pLMeQ8YKWeMucdbVdhvYrjbahkUin',  // _DSC2768.JPG
  'https://lh3.googleusercontent.com/d/1meWjC81xKvuWNT0cJ6dDPGJO_Fvcbjpa',  // _DSC2769.JPG
  'https://lh3.googleusercontent.com/d/1vVK4yXWdYwz4C7VWQ88xspSRxqtrd1uO',  // _DSC2770.JPG
  'https://lh3.googleusercontent.com/d/13ad2J0Kinx2NtZ-22x8fOaOVWGx45N-l',  // _DSC2771.JPG
  'https://lh3.googleusercontent.com/d/1MLk6PYBTVbLq_qJdAp7hxNlDpg0s0Cf_',  // _DSC2772.JPG
  'https://lh3.googleusercontent.com/d/1_Z6ipbhaptcK0wH7IvYq_l96V6P0SRef',  // _DSC2774.JPG
  'https://lh3.googleusercontent.com/d/1PelXrX737tvkee1Nd-YdSqXM2U1p7Ukt',  // _DSC2776.JPG
  'https://lh3.googleusercontent.com/d/1A79vpltCo5Li_-Zyso_TAMRsvdVnHpJC',  // _DSC2778.JPG
  'https://lh3.googleusercontent.com/d/1z3rKveUwvsvefrMphfZy6hUZuC5ZdOkW',  // _DSC2781.JPG
  'https://lh3.googleusercontent.com/d/1MxVrisOZG68hqVg9QWWc-RAMzLa6kesH',  // _DSC2783.JPG
  'https://lh3.googleusercontent.com/d/1Ljahr9OcnNNuBXMzQQV57KikHfcXJLe4',  // _DSC2784.JPG
  'https://lh3.googleusercontent.com/d/1xaoszdpiQz4mfOhQCVzVoOCUwacB5k8R',  // _DSC2785.JPG
  'https://lh3.googleusercontent.com/d/19RAsDxE0s8P6n2mzo1UIHHNPxWLnzAje',  // _DSC2786.JPG
  'https://lh3.googleusercontent.com/d/1-JvmWPkMVEw3zxOuveD3-MysUFozdabY',  // _DSC2787.JPG
  'https://lh3.googleusercontent.com/d/1PZugw3xtH8fFx_NfF9RGyV2E44_fhjc0',  // _DSC2789.JPG
  'https://lh3.googleusercontent.com/d/1mRWVJXbUr1msii_nb8BMP-FOTOJ4g6um',  // _DSC2791.JPG
  'https://lh3.googleusercontent.com/d/16IWWOT4bMTrYNYMxwNTWB6TXFs2yhqpU',  // _DSC2793.JPG
  'https://lh3.googleusercontent.com/d/1wBymnPmjxvLMYqpoNnjsF_snPjHZzFtw',  // _DSC2794.JPG
  'https://lh3.googleusercontent.com/d/1bhP3Hb9-YiktNvG0mxUUmH7auz6Kv0jq',  // _DSC2796.JPG
  'https://lh3.googleusercontent.com/d/1mWAz9UMzxOm0T8xDwqgZpdb1HeN_nuNC',  // _DSC2797.JPG
  'https://lh3.googleusercontent.com/d/1BRiEvF2tHkNERY2yJszA3fDrfA5BHhGh',  // _DSC2798.JPG
  'https://lh3.googleusercontent.com/d/1c690xsWvjA2sThyVb6IuwKObWwv5zrSU',  // _DSC2801.JPG
  'https://lh3.googleusercontent.com/d/1jocvR1lHANTekBBX9XtvZw4O_gJdbuir',  // _DSC2803.JPG
  'https://lh3.googleusercontent.com/d/1xlItyjJHu0FVnmE9GLbiTJfzz7Or1bPY',  // _DSC2805.JPG
  'https://lh3.googleusercontent.com/d/1zfqIIBEcsp54TlnBR-j84yL7SDX-qHLN',  // _DSC2806.JPG
  'https://lh3.googleusercontent.com/d/1-Z-1VDTDtpgY7frKDYlLqUtOyfg9X1C_',  // _DSC2807.JPG
  'https://lh3.googleusercontent.com/d/1i7Sft_2Zre8yOYUx-UFFXXbP-oKx59Fp',  // _DSC2808.JPG
  'https://lh3.googleusercontent.com/d/1u2Uow8hP9WDh8cfzKfMGpLWKVo20MXB0',  // _DSC2809.JPG
  'https://lh3.googleusercontent.com/d/1XrSrpiajLj4ObL3zyBnog0kC1ZXTd19l',  // _DSC2810.JPG
  'https://lh3.googleusercontent.com/d/1WN-ySzigdBoHXOJBlScqjHj_8As9uNa1',  // _DSC2812.JPG
  'https://lh3.googleusercontent.com/d/1B0tM27GFjFDmdoovd66mv7nR05XT-gr9',  // _DSC2814.JPG
  'https://lh3.googleusercontent.com/d/1e2kLZ24sO1xB_9r905RxR6JLH9IojjD6',  // _DSC2815.JPG
  'https://lh3.googleusercontent.com/d/1rRMYcAawkHK34IV7gkoDv2F_Nn1p9jhD',  // _DSC2816.JPG
  'https://lh3.googleusercontent.com/d/1eYeRwFoIOf4pQqjaj0lNkQm_q1VlEJ0A',  // _DSC2818.JPG
  'https://lh3.googleusercontent.com/d/1tTYindN26-0hTK6jh_eB02hNkVSONAaN',  // _DSC2819.JPG
  'https://lh3.googleusercontent.com/d/1oPJEOr1TMkURJ_idsua8L55LHnJmQASN',  // _DSC2822.JPG
  'https://lh3.googleusercontent.com/d/1YirUSLuFue7YtEJStt62XJAxJA6l85Ld',  // _DSC2823.JPG
  'https://lh3.googleusercontent.com/d/1fU3VqUD3wW_sDrcZulnBnZgUGi_WlsBE',  // _DSC2825.JPG
  'https://lh3.googleusercontent.com/d/1A9DFpG9TU55W6Stpdl9Nx2mYm5zB1U7-',  // _DSC2826.JPG
  'https://lh3.googleusercontent.com/d/16kutuqigBpCp-U6cSdliOEDzcdvtjTvF',  // _DSC2830.JPG
  'https://lh3.googleusercontent.com/d/1LNchspdYRLf-Ub4mGAkRKnigIMTF1kuy',  // _DSC2831.JPG
  'https://lh3.googleusercontent.com/d/1w5BO8sWRKYDwrZaWrx5t1TaN94HyBe71',  // _DSC2836.JPG
  'https://lh3.googleusercontent.com/d/10NN-CJ5HZcBHwatCxlKZVY_9Rd1Gan13',  // _DSC2837.JPG
  'https://lh3.googleusercontent.com/d/1woaAIdd17sQtfuhMkgt506smQ2nVNJ9L',  // _DSC2843.JPG
  'https://lh3.googleusercontent.com/d/1c7VqNH74eoJtLzs5PodkhyK9SCHYH_ch',  // _DSC2845.JPG
  'https://lh3.googleusercontent.com/d/1GD0A3ndSAoJVA1nMqtWjBUo-w5sRu6Ta',  // _DSC2846.JPG
  'https://lh3.googleusercontent.com/d/1ZRjLZIDej63pUmMA5iK9nMN9N8MBqR4u',  // _DSC2847.JPG
  'https://lh3.googleusercontent.com/d/1xhmJIKuodrFOpEI16xNkU6AH7Ck7_aEP',  // _DSC2848.JPG
  'https://lh3.googleusercontent.com/d/1rS0u4-Y1ouB-rrwLC3y4U4vIT8vQNQFi',  // _DSC2849.JPG
  'https://lh3.googleusercontent.com/d/162eot8ecrNxJMfTAczCMWNrkdnd_TPy3',  // _DSC2852.JPG
  'https://lh3.googleusercontent.com/d/15B9PrEdeYzIwM6TjpDiV0EimLDWji-wK',  // _DSC2853.JPG
  'https://lh3.googleusercontent.com/d/1ddBViskFoUe4k42ZltKXcrXl4TYLB0q9',  // _DSC2855.JPG
  'https://lh3.googleusercontent.com/d/1oygiSoF4XYFrwyzTuLBAaCkkWcpIQ-56',  // _DSC2856.JPG
  'https://lh3.googleusercontent.com/d/1K_rGCroMUVKC5Ht20Jkx1xrlNskdm2al',  // _DSC2861.JPG
  'https://lh3.googleusercontent.com/d/1SPPsQOMLM-qGQW_7zvbsgcOsuHJyg-MK',  // _DSC2864.JPG
  'https://lh3.googleusercontent.com/d/1XCWXIu6idtzQL7BjK3M_auCQO4lcGMX_',  // _DSC2865.JPG
  'https://lh3.googleusercontent.com/d/1MI_gZwI_VUlByYF4tNWnjg28O9-tGUYW',  // _DSC2869.JPG
  'https://lh3.googleusercontent.com/d/1EIzzGjaokV8iX_lnD0aR0HBgEZ7STKmE',  // _DSC2870.JPG
  'https://lh3.googleusercontent.com/d/1thPMLb2v4Lv1sh2Ci8LiCl18vSr1mfdW',  // _DSC2871.JPG
  'https://lh3.googleusercontent.com/d/1Vu91QMOcDQW2RYXdhEGZZcLLwej1cqI7',  // _DSC2874.JPG
  'https://lh3.googleusercontent.com/d/176oH089uOfqhkWeI21xendXbPFHwJrDc',  // _DSC2876.JPG
  'https://lh3.googleusercontent.com/d/1xuJhpvN5s0cluX6jfALz4_OuKFoE6Z0Y',  // _DSC2877.JPG
  'https://lh3.googleusercontent.com/d/1W13-_5F5zHVXRlCZa3JvvqIyxsVLdV6A',  // _DSC2878.JPG
  'https://lh3.googleusercontent.com/d/1fO2DESOqz-GiTuAhbPXxRAYuIUSFiUuv',  // _DSC2880.JPG
  'https://lh3.googleusercontent.com/d/1QfLb30EWFMn_jhY2S9LTDksWY17aZgS0',  // _DSC2881.JPG
  'https://lh3.googleusercontent.com/d/1BOhWiTMssv57UZJeSJ_vL3WVruIw73KK',  // _DSC2883.JPG
  'https://lh3.googleusercontent.com/d/1gfg24dWUc9tQYG2wlxNA9hhBrdAGYl-F',  // _DSC2884.JPG
  'https://lh3.googleusercontent.com/d/193NR_XyZlgzV9k3SORl9obQ21JtBgD0C',  // _DSC2885.JPG
  'https://lh3.googleusercontent.com/d/1otDytJ0_dIqz7AfjP5O1JaEn3dV9Z1eN',  // _DSC2887.JPG
  'https://lh3.googleusercontent.com/d/1l-M7xpXP7wFTLNkfo39bXEmF8NQ3Z5u7',  // _DSC2889.JPG
  'https://lh3.googleusercontent.com/d/1tLMUnJw1-ruWbg_9mzU9qqMnZ4l2TgQW',  // _DSC2890.JPG
  'https://lh3.googleusercontent.com/d/1TdUxSnyKOTsp1V8UrAZH9qegQxkJX3Cc',  // _DSC2891.JPG
  'https://lh3.googleusercontent.com/d/1U-UO6v-dGsOew8bYRZM4yY0CxEL4xX8c',  // _DSC2895.JPG
  'https://lh3.googleusercontent.com/d/1aPwRPhwQpgCiSDXCA6yKwQyJiddd3o5J',  // _DSC2896.JPG
  'https://lh3.googleusercontent.com/d/1dKcdJcFzgcSQojvns_T4146ed9E_dUjX',  // _DSC2897.JPG
  'https://lh3.googleusercontent.com/d/1Jni3sSSYveEBZBJNuSnM8fmAC5TayeCS',  // _DSC2899.JPG
  'https://lh3.googleusercontent.com/d/1kDqGJbgeLdAgVlPVAniYin2PYaDWGYDf',  // _DSC2900.JPG
  'https://lh3.googleusercontent.com/d/1Kdbtuo_6K_szZGZPCqefCD1LpZDkvsCY',  // _DSC2901.JPG
  'https://lh3.googleusercontent.com/d/1LZvmj-nFfdAo875PzcOmwhFgId3HYXVq',  // _DSC2902.JPG
  'https://lh3.googleusercontent.com/d/1sdda82IDEBqnKKD_EJnEHidsFbmhDjEq',  // _DSC2904.JPG
  'https://lh3.googleusercontent.com/d/15OpWKSSV4Kl5ImKH5qj_5wERM7k6-29I',  // _DSC2905.JPG
  'https://lh3.googleusercontent.com/d/1imlxgFM3mpNk7bhm7QU0pY_D5irA205o',  // _DSC2906.JPG
  'https://lh3.googleusercontent.com/d/1jsBIfc8xTWEU3ZrPIpMCZHHcI45avb7b',  // _DSC2907.JPG
  'https://lh3.googleusercontent.com/d/1cNMDIZKzOkBJGmKIHiPUU5r-KcGDjZ9X',  // _DSC2908.JPG
  'https://lh3.googleusercontent.com/d/1jTy0wZvRTof8oEF2E7MYGl8ulMdmGoML',  // _DSC2909.JPG
  'https://lh3.googleusercontent.com/d/1RC1N4Ic1HVSEpB4YJNKCqApC7M48VH5j',  // _DSC2911.JPG
  'https://lh3.googleusercontent.com/d/18clJi92R31v3rXftOVXCnbNW5s8uKBtx',  // _DSC2914.JPG
  'https://lh3.googleusercontent.com/d/1FYQMjLPb56TNg5K2vc_hGF5WJ7a58cFD',  // _DSC2915.JPG
  'https://lh3.googleusercontent.com/d/1Go_vj68KyZB87qjeWc7wFCwFbZJTxiv3',  // _DSC2916.JPG
  'https://lh3.googleusercontent.com/d/1FPdeayaUPNBmvG_r7xXbwNuNjHL1_PYG',  // _DSC2918.JPG
  'https://lh3.googleusercontent.com/d/1LPLlg3p8_adMYXk1Mu-Zq_-y1vTlq_4p',  // _DSC2919.JPG
  'https://lh3.googleusercontent.com/d/1z2Ng7KvfWfBpoGY1XjRiBZZ7vvyTyFAd',  // _DSC2923.JPG
  'https://lh3.googleusercontent.com/d/1mcnxLxTZ0Zx9rD68tr6BoxotfJiw7nRA',  // _DSC2924.JPG
  'https://lh3.googleusercontent.com/d/1vK3lWm98bOl0pSXw79BneD19f_4RXrKW',  // _DSC2925.JPG
  'https://lh3.googleusercontent.com/d/1fJJIPPnboyGUziEbf0bYRihDpv0LtTsO',  // _DSC2926.JPG
  'https://lh3.googleusercontent.com/d/1LF7jAELOX_S0u7wAuvRvoZHyuHZ3lDyH',  // _DSC2928.JPG
  'https://lh3.googleusercontent.com/d/1ss2F-2V0yeLDLBS-J22P0rIWDTU65R1t',  // _DSC2930.JPG
  'https://lh3.googleusercontent.com/d/11_83v1uDVtdOqxTDvzsHjvqZVm4FyxOv',  // _DSC2931.JPG
  'https://lh3.googleusercontent.com/d/15PuRezpDB3uZ0N-XMsbjvAm_zUZrbyyt',  // _DSC2933.JPG
  'https://lh3.googleusercontent.com/d/1MsG8eZ37iT2L0Rslkp6pzwRsdSCFK2Y9',  // _DSC2938.JPG
  'https://lh3.googleusercontent.com/d/1DWwCOCSNFSEmoCe66nFF5XnCQzV1l1lc',  // _DSC2939.JPG
  'https://lh3.googleusercontent.com/d/1uJaL6i5tDCjVGDcTfxf5ikxOAf_EzlNo',  // _DSC2940.JPG
  'https://lh3.googleusercontent.com/d/1B905ixPtnBzcnHCvaQPOtbP150TYSIHK',  // _DSC2941.JPG
  'https://lh3.googleusercontent.com/d/1opxWPGDGlEt39Ztjp0H1Be3X3o0Evfh4',  // _DSC2944.JPG
  'https://lh3.googleusercontent.com/d/1QRyQjoJ02hALo2-e2zMTy0Cc6j9760Yu',  // _DSC2945.JPG
  'https://lh3.googleusercontent.com/d/1Zuv6lBFNZPYJiHej9-uqTwsdeMq_1V3D',  // _DSC2946.JPG
  'https://lh3.googleusercontent.com/d/1X75T7_OUyyWAH5YdJeh45RSsc7-rNsry',  // _DSC2947.JPG
  'https://lh3.googleusercontent.com/d/1V6CKD_7Ayoio6uL55DlhD4hfZCwidGk2',  // _DSC2948.JPG
  'https://lh3.googleusercontent.com/d/14iKGd0qJeksEGzw6feOlWxNZ2-EnXx3N',  // _DSC2949.JPG
  'https://lh3.googleusercontent.com/d/122OjlAb2xKlLmHGoOW14USm1GdGwOGBj',  // _DSC2950.JPG
  'https://lh3.googleusercontent.com/d/1VLAGXhILoGTpqth2WVjeHqOXQ8MIoXgo',  // _DSC2951.JPG
  'https://lh3.googleusercontent.com/d/1FTYlewgVjazEanC4fJs1znTaVQG8eDFC',  // _DSC2952.JPG
  'https://lh3.googleusercontent.com/d/1gKzACEN5kCrmpV_UQLoJc5385NpfymL_',  // _DSC2953.JPG
  'https://lh3.googleusercontent.com/d/1-_oNxVw6bZineuJJm5k4kpjtCvKg-FEB',  // _DSC2955.JPG
  'https://lh3.googleusercontent.com/d/1brAYr11grjvjuhWgUx6tBo-fhjiyQCRY',  // _DSC2956.JPG
  'https://lh3.googleusercontent.com/d/1VIY1k4a13pSSAQOjYzhqx4u--LtqIE8Q',  // _DSC2959.JPG
  'https://lh3.googleusercontent.com/d/1BWCCKk8T4F85BnlcK8xTMBFCJkZxJ3c3',  // _DSC2961.JPG
  'https://lh3.googleusercontent.com/d/1cNEMBFHpaJLRVfIKV65qDj2nypIgK0Md',  // _DSC2963.JPG
  'https://lh3.googleusercontent.com/d/19ZMs6WoMXYfBgjuPDwxcI9WOB7ZIhhx0',  // _DSC2964.JPG
  'https://lh3.googleusercontent.com/d/1fuysx-IDaaKSmlC8NJGNl9nb4bScQx4V',  // _DSC2965.JPG
  'https://lh3.googleusercontent.com/d/1jt0ZY42GatdyxqX_fheP5ZpYeDJcpu45',  // _DSC2968.JPG
  'https://lh3.googleusercontent.com/d/1qKF6xPuj1gRbOtHxCjMO35k5gRTP3oqu',  // _DSC2969.JPG
  'https://lh3.googleusercontent.com/d/1ruMQWEUn9cYZxicmYskFEXYLle0OoO38',  // _DSC2971.JPG
  'https://lh3.googleusercontent.com/d/15GrJasZkUCBK5Ef67240xYbjA6J5nEyY',  // _DSC2975.JPG
  'https://lh3.googleusercontent.com/d/1TFl9HBbHk6pqv3Dane2VlSvA37Gq7UJj',  // _DSC2976.JPG
  'https://lh3.googleusercontent.com/d/18LVk4bMWjSSCTWNLkbmbmiw2I7yp7jvQ',  // _DSC2979.JPG
  'https://lh3.googleusercontent.com/d/1r4kM4xHmvS2RDNMJ9jPI7nO7DawuuGGk',  // _DSC2980.JPG
  'https://lh3.googleusercontent.com/d/1TyMxKl0F_3OmzCk80oHIOGcFFhp55N90',  // _DSC2981.JPG
  'https://lh3.googleusercontent.com/d/1pMxSUvPa-h4IzTftLQufQzLT2GCGaZO9',  // _DSC2982.JPG
  'https://lh3.googleusercontent.com/d/15d7gXs1_LDG_Nu-Un3e5xw-FNscjp10t',  // _DSC2983.JPG
  'https://lh3.googleusercontent.com/d/1veO-DfJLn8WI4DgFd4_cjTIL5Goe_12k',  // _DSC2984.JPG
  'https://lh3.googleusercontent.com/d/1s42zuvHdiiwnusR26MSCxXKPgtXHELev',  // _DSC2985.JPG
  'https://lh3.googleusercontent.com/d/1FkUEeNzOqqKO4_yX9NyVn3Y3piRX0OhH',  // _DSC2986.JPG
  'https://lh3.googleusercontent.com/d/1FeNaxMX6yqA1Tus7T5Ii7tBuiLdHES2v',  // _DSC2987.JPG
  'https://lh3.googleusercontent.com/d/12gdkHbEIeqs7ZnHqM-Viz6mwqW2m6w_h',  // _DSC2988.JPG
  'https://lh3.googleusercontent.com/d/16Mhgtq5RNMFDqmi5BOMPbQO2LFdGqYne',  // _DSC2991.JPG
  'https://lh3.googleusercontent.com/d/1BOGmrQhT0I1n1_Z8DAPwje-4cIpEeFFF',  // _DSC2992.JPG
  'https://lh3.googleusercontent.com/d/1uNew7B5MK6H7FBrfU8RG-dvV3lK4CuBm',  // _DSC2996.JPG
  'https://lh3.googleusercontent.com/d/1Y5MNsOClV2gaqBWBquHFVt3ZHFgGh60i',  // _DSC2997.JPG
  'https://lh3.googleusercontent.com/d/1ekRcy7kW-2h7IKY5aYnNn776epPHiRYg',  // _DSC2998.JPG
  'https://lh3.googleusercontent.com/d/12uYqKrfLAB8hIxBnd6wmYWiOb0KhzORs',  // _DSC3001.JPG
  'https://lh3.googleusercontent.com/d/1UhDScduPksxQ3q4-xNepJ_IBjhWCj8xz',  // _DSC3003.JPG
  'https://lh3.googleusercontent.com/d/1es_QuTZ8koijERhGOTX6eLeQ9ptvfPF5',  // _DSC3012.JPG
  'https://lh3.googleusercontent.com/d/1dI28sx7TBEUKEGwlpO81Z7IinP29sJzt',  // _DSC3013.JPG
  'https://lh3.googleusercontent.com/d/1VfLEP4eUOiUaWWOacT7Z1HWn28vTIUby',  // _DSC3014.JPG
  'https://lh3.googleusercontent.com/d/1qukOjuym97yQLuqshAIXu60b23D81KK0',  // _DSC3015.JPG
  'https://lh3.googleusercontent.com/d/1TwMBhjuspCjZQ76jjZP_Dn9lj-cUUuOP',  // _DSC3017.JPG
  'https://lh3.googleusercontent.com/d/1zPkq30z6HIVcHL3tTMXpljLYJHMACBXx',  // _DSC3018.JPG
  'https://lh3.googleusercontent.com/d/1lXRkKM16QUUxmnlcNwnsGhkn5mLFTuNh',  // _DSC3021.JPG
  'https://lh3.googleusercontent.com/d/1gFKlyjLQ2tHMcMnVrH5AmsX8RLuTu6nz',  // _DSC3022.JPG
  'https://lh3.googleusercontent.com/d/1OkMoG82Gk_nVaArf-wWWp7-kQ_nqzWfY',  // _DSC3023.JPG
  'https://lh3.googleusercontent.com/d/1SN67uenV5tq3CEcjMAplp6EVv8A8c1ts',  // _DSC3024.JPG
  'https://lh3.googleusercontent.com/d/1JXkKQnZQtYWie2j8t3xtK3nA37kuK-oE',  // _DSC3025.JPG
  'https://lh3.googleusercontent.com/d/14ptgZPjvI8miFD0C777GA6H1C8iHGozB',  // _DSC3026.JPG
  'https://lh3.googleusercontent.com/d/1PKhDX7ePPGqvqNOGJ-2v0YZWRSA5doTv',  // _DSC3027.JPG
  'https://lh3.googleusercontent.com/d/1z6BNpsIbB9e7Pp_oZrNT1RFUPDIwPXgc',  // _DSC3028.JPG
  'https://lh3.googleusercontent.com/d/1EVYkZCAzprwNKkvahsFFpxKCRVbbDtMz',  // _DSC3029.JPG
  'https://lh3.googleusercontent.com/d/11VimW6UBB9zPIW1yfH-HkB0RcTCHad76',  // _DSC3034.JPG
  'https://lh3.googleusercontent.com/d/1L73f7RPux41-esgO1-yqT3fLmDi9Hgy3',  // _DSC3035.JPG
  'https://lh3.googleusercontent.com/d/1E3PMyFxCTM6pTQzCV6ikP6rHS0Jn9ugJ',  // _DSC3039.JPG
  'https://lh3.googleusercontent.com/d/1B_TZ_EGe3hrRI7e-uPFPGgvrJPy8vu2z',  // _DSC3040.JPG
  'https://lh3.googleusercontent.com/d/1MM2hW9ElyevqLVcdGA58SkjUPKH0f1z6',  // _DSC3041.JPG
  'https://lh3.googleusercontent.com/d/1Z3sd9osltY3rnrtq2piZvC-uHvp9mb7Y',  // _DSC3047.JPG
  'https://lh3.googleusercontent.com/d/1sOFLtqM0OawuCtwcCBdvWQfGvKw2OFjK',  // _DSC3048.JPG
  'https://lh3.googleusercontent.com/d/11pWtgff70PxG14sncR1zgqdv71zB0X2n',  // _DSC3053.JPG
  'https://lh3.googleusercontent.com/d/18kgRRWRiG4Ab8IU0U0gWsJ2SQVUZt0nn',  // _DSC3054.JPG
  'https://lh3.googleusercontent.com/d/1S82UzYUVwAYcyf7jqlCfYzNkq7mWC-0J',  // _DSC3055.JPG
  'https://lh3.googleusercontent.com/d/1dWjqtzTl2qalSJhinmQ1Hu6-KC8BTkt0',  // _DSC3056.JPG
  'https://lh3.googleusercontent.com/d/1p4hNnD9EXjTjgwl5-dVJKwNZSAht1u8N',  // _DSC3058.JPG
  'https://lh3.googleusercontent.com/d/1Yxy-Qh88ojP2fLrPCBr3b-_vQUbcYCVp',  // _DSC3059.JPG
  'https://lh3.googleusercontent.com/d/1CrEmnruDMqgD4EExLvK_8lN_cN5lpUNM',  // _DSC3061.JPG
  'https://lh3.googleusercontent.com/d/1VL-C5Cr3uKQCy_f-IohTrll7ZADcuaHI',  // _DSC3063.JPG
  'https://lh3.googleusercontent.com/d/13ZrRDemo8Ul2uiwH0d0o5O-l7ePJFgtS',  // _DSC3065.JPG
  'https://lh3.googleusercontent.com/d/1xAgJMehjeAyU9rME-lwjYiHX9CbL1o8R',  // _DSC3066.JPG
  'https://lh3.googleusercontent.com/d/1_qf-HCeHiE_QY4lxbOWXcJ3t61-Yu5Kw',  // _DSC3067.JPG
  'https://lh3.googleusercontent.com/d/1-iYfWG_W4xDIF8Ufu-C0gvqROxEdgH4u',  // _DSC3068.JPG
  'https://lh3.googleusercontent.com/d/1rFjBFAb0_vnt8RxCPAw63wxPzBMZYuRj',  // _DSC3070.JPG
  'https://lh3.googleusercontent.com/d/1oAtDVv4NR66dR_xzAUes5y9tHXFmVhgF',  // _DSC3075.JPG
  'https://lh3.googleusercontent.com/d/154Q_nyUYoNwTWnRUSv_FpPf9ofjFtY_U',  // _DSC3082.JPG
  'https://lh3.googleusercontent.com/d/1IQ_f3KW16SB2SMYEwL5njh_tlA3tDF2k',  // _DSC3083.JPG
  'https://lh3.googleusercontent.com/d/1-biHhWt2oMV6r2-jMWnmbrCsBGnRZmAE',  // _DSC3092.JPG
  'https://lh3.googleusercontent.com/d/17su0En-ubDUUSbHPr1gGzF56zI_lxbyP',  // _DSC3098.JPG
  'https://lh3.googleusercontent.com/d/1V8UG8Tu1Z2_ic8Crf2-T5-KmAcdhbXBL',  // _DSC3099.JPG
  'https://lh3.googleusercontent.com/d/1koecy5xDgsbwySVIwebERQBSUfcO6-B2',  // _DSC3100.JPG
  'https://lh3.googleusercontent.com/d/1hIUkSOxQElBO1yoBansUHDHkcQyj0HGb',  // _DSC3101.JPG
  'https://lh3.googleusercontent.com/d/1dlpFAUtWcdagbTSFQirmmgrTYdZx3gFT',  // _DSC3102.JPG
  'https://lh3.googleusercontent.com/d/1qzi3BqUgRzQHJnXBB5TqXGD9EJjGZy-t',  // _DSC3103.JPG
  'https://lh3.googleusercontent.com/d/1DVx--ZCQz1s2AFrk37r03Dgo_e02ktfi',  // _DSC3105.JPG
  'https://lh3.googleusercontent.com/d/14jnsU6tpoU3eRIXiz2LtB33ni4hnDKHL',  // _DSC3106.JPG
  'https://lh3.googleusercontent.com/d/1yCHFvBIUv88bkk-e_zFMCzqZ_P5VsemB',  // _DSC3107.JPG
  'https://lh3.googleusercontent.com/d/16Xg3aOssA89-iveOCnAN9c5Ur3NzCM83',  // _DSC3108.JPG
  'https://lh3.googleusercontent.com/d/1Kd7HGc7cgC4uM6Icx4xjmQ2P276NUFH4',  // _DSC3109.JPG
  'https://lh3.googleusercontent.com/d/1TaatV2r3NAy4bE0CLXxGGXLWzvoq4chh',  // _DSC3110.JPG
  'https://lh3.googleusercontent.com/d/1vlBIonsXf8kI1_M0nYmOTtx_dTYPF46c',  // _DSC3111.JPG
  'https://lh3.googleusercontent.com/d/1zMu1m6oWVMYXbFoUROxYvQqZm99_a1rC',  // _DSC3112.JPG
];

const BATCH   = 30;
let shown     = 0;

const grid    = document.getElementById('galleryGrid');
const countEl = document.getElementById('galleryCount');
const btnMore = document.getElementById('btnLoadMore');
const btnAll  = document.getElementById('btnLoadAll');

// ── Column management ─────────────────────────────────────────────────
let colEls  = [];
let nextCol = 0;

function getColCount() {
  const w = window.innerWidth;
  if (w >= 1200) return 4;
  if (w >= 900)  return 3;
  if (w >= 600)  return 2;
  return 1;
}

function initGrid() {
  grid.innerHTML = '';
  colEls  = [];
  nextCol = 0;
  const n = getColCount();
  for (let i = 0; i < n; i++) {
    const col = document.createElement('div');
    col.className = 'gallery-col';
    grid.appendChild(col);
    colEls.push(col);
  }
}

function updateCount() {
  countEl.textContent = `Showing ${shown} of ${images.length} photos`;
  btnMore.disabled = shown >= images.length;
  btnAll.disabled  = shown >= images.length;
}

function addItems(start, end) {
  for (let i = start; i < end && i < images.length; i++) {
    const item = document.createElement('div');
    item.className = 'gallery-item';

    const img = document.createElement('img');
    img.src      = images[i];
    img.alt      = `Barat ceremony photo ${i + 1}`;
    img.loading  = 'lazy';
    img.decoding = 'async';
    img.onload  = () => img.classList.add('loaded');
    img.onerror = () => img.classList.add('loaded');

    const overlay = document.createElement('div');
    overlay.className = 'item-overlay';
    overlay.innerHTML = '<span class="zoom-icon">⊕</span>';

    item.appendChild(img);
    item.appendChild(overlay);
    addMehndiCorners(item);
    item.addEventListener('click', () => openLightbox(i));
    colEls[nextCol % colEls.length].appendChild(item);
    nextCol++;
  }
}

function loadMore() {
  const next = Math.min(shown + BATCH, images.length);
  addItems(shown, next);
  shown = next;
  updateCount();
}

function loadAll() {
  addItems(shown, images.length);
  shown = images.length;
  updateCount();
}

btnMore.addEventListener('click', loadMore);
btnAll.addEventListener('click', loadAll);
initGrid();
loadMore();

// ── Lightbox ──────────────────────────────────────────────────────────
const lightbox      = document.getElementById('lightbox');
const lbImg         = document.getElementById('lb-img');
const lbCounter     = document.getElementById('lb-counter');
const lbClose       = document.getElementById('lb-close');
const lbPrev        = document.getElementById('lb-prev');
const lbNext        = document.getElementById('lb-next');
const lbPlay        = document.getElementById('lb-play');
const lbProgressBar = document.getElementById('lb-progress-bar');
let currentIdx      = 0;

function openLightbox(idx) {
  currentIdx = idx;
  setLbImage(idx);
  lightbox.classList.add('active');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  stopSlideshow();
  resetZoom();
  lightbox.classList.remove('active');
  document.body.style.overflow = '';
}

function setLbImage(idx) {
  lbImg.classList.add('loading');
  const tmp = new Image();
  tmp.onload = () => { lbImg.src = tmp.src; lbImg.classList.remove('loading'); };
  tmp.src = images[idx];
  lbCounter.textContent = `${idx + 1} / ${images.length}`;
}

function lbGo(dir) {
  resetZoom();
  currentIdx = (currentIdx + dir + images.length) % images.length;
  setLbImage(currentIdx);
  if (slideshowActive) restartProgress();
}

lbClose.addEventListener('click', closeLightbox);
lbPrev.addEventListener('click', () => lbGo(-1));
lbNext.addEventListener('click', () => lbGo(1));
lightbox.addEventListener('click', (e) => { if (e.target === lightbox) closeLightbox(); });
document.addEventListener('keydown', (e) => {
  if (!lightbox.classList.contains('active')) return;
  if (e.key === 'Escape')     closeLightbox();
  if (e.key === 'ArrowLeft')  lbGo(-1);
  if (e.key === 'ArrowRight') lbGo(1);
  if (e.key === ' ')          toggleSlideshow();
});

// ── Slideshow ─────────────────────────────────────────────────────────
const SLIDESHOW_MS  = 3500;
let slideshowActive = false;
let slideshowTimer  = null;

function startSlideshow() {
  slideshowActive = true;
  lbPlay.classList.add('playing');
  lbPlay.innerHTML = '&#9646;&#9646;';
  lbPlay.setAttribute('aria-label', 'Pause slideshow');
  restartProgress();
}

function stopSlideshow() {
  slideshowActive = false;
  clearTimeout(slideshowTimer);
  lbPlay.classList.remove('playing');
  lbPlay.innerHTML = '&#9654;';
  lbPlay.setAttribute('aria-label', 'Play slideshow');
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
}

function toggleSlideshow() { slideshowActive ? stopSlideshow() : startSlideshow(); }

function restartProgress() {
  clearTimeout(slideshowTimer);
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
  void lbProgressBar.offsetWidth;
  lbProgressBar.style.transition = `width ${SLIDESHOW_MS}ms linear`;
  lbProgressBar.style.width = '100%';
  slideshowTimer = setTimeout(() => { if (slideshowActive) lbGo(1); }, SLIDESHOW_MS);
}

lbPlay.addEventListener('click', toggleSlideshow);

// ── Pinch-to-Zoom & Pan ───────────────────────────────────────────────
let scale = 1, panX = 0, panY = 0;
let isPinching = false, initDist = 0, initScale = 1;
let isDragging = false, dragStartX = 0, dragStartY = 0, dragPanX = 0, dragPanY = 0;
let lastTap = 0;

function applyTransform(animated) {
  if (animated) { lbImg.style.transition = 'transform 0.25s ease'; setTimeout(() => { lbImg.style.transition = ''; }, 260); }
  else { lbImg.style.transition = ''; }
  lbImg.style.transform = `translate(${panX}px, ${panY}px) scale(${scale})`;
  lbImg.classList.toggle('zoomed', scale > 1);
}

function resetZoom() {
  scale = 1; panX = 0; panY = 0;
  lbImg.style.transition = 'transform 0.25s ease';
  lbImg.style.transform = '';
  lbImg.classList.remove('zoomed', 'dragging');
  setTimeout(() => { lbImg.style.transition = ''; }, 260);
}

function getDist(t) { return Math.hypot(t[0].clientX - t[1].clientX, t[0].clientY - t[1].clientY); }

lbImg.addEventListener('touchstart', (e) => {
  if (e.touches.length === 2) {
    isPinching = true; isDragging = false;
    initDist = getDist(e.touches); initScale = scale; e.preventDefault();
  } else if (e.touches.length === 1) {
    const now = Date.now();
    if (now - lastTap < 280) { lastTap = 0; scale > 1 ? resetZoom() : (scale = 2.5, applyTransform(true)); e.preventDefault(); return; }
    lastTap = now;
    if (scale > 1) { isDragging = true; dragStartX = e.touches[0].clientX; dragStartY = e.touches[0].clientY; dragPanX = panX; dragPanY = panY; lbImg.classList.add('dragging'); e.preventDefault(); }
  }
}, { passive: false });

lbImg.addEventListener('touchmove', (e) => {
  if (isPinching && e.touches.length === 2) { scale = Math.min(Math.max(initScale * (getDist(e.touches) / initDist), 1), 4); applyTransform(false); e.preventDefault(); }
  else if (isDragging && e.touches.length === 1 && scale > 1) { panX = dragPanX + (e.touches[0].clientX - dragStartX); panY = dragPanY + (e.touches[0].clientY - dragStartY); applyTransform(false); e.preventDefault(); }
}, { passive: false });

lbImg.addEventListener('touchend', (e) => {
  if (e.touches.length < 2) isPinching = false;
  if (e.touches.length === 0) { isDragging = false; lbImg.classList.remove('dragging'); if (scale < 1.08) resetZoom(); }
});

let swipeStartX = 0, swipeStartY = 0;
lightbox.addEventListener('touchstart', (e) => { if (e.target === lbImg) return; swipeStartX = e.touches[0].clientX; swipeStartY = e.touches[0].clientY; }, { passive: true });
lightbox.addEventListener('touchend', (e) => {
  if (e.target === lbImg || scale > 1) return;
  const dx = e.changedTouches[0].clientX - swipeStartX;
  const dy = e.changedTouches[0].clientY - swipeStartY;
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) lbGo(dx < 0 ? 1 : -1);
});
