// -- All Engagement Images ---------------------------------------------------
// Auto-generated by tools/get-drive-images.js  (2026-03-25)
// Source folder: Engagement  (178 images)
const images = [
  'https://lh3.googleusercontent.com/d/1U8bSoX96h6v5xMx3rm2ejc_hl62v59Oq',  // DSC_7947.JPG
  'https://lh3.googleusercontent.com/d/1GDyiSEUzMu0oyn8CiFtkEUOkyYuoSpA4',  // DSC_7948.JPG
  'https://lh3.googleusercontent.com/d/1Mjz1K8qB3MI_SZlcLiNZl8fPl4N2wjNW',  // DSC_7949.JPG
  'https://lh3.googleusercontent.com/d/1-YrcqjdUAOEq4Obm07LVysch1Vr2unZS',  // DSC_7950.JPG
  'https://lh3.googleusercontent.com/d/1QBnUkMg7aWGAppNo0D1k7T9xHoDtrPS-',  // DSC_7951.JPG
  'https://lh3.googleusercontent.com/d/1pqk_wkEsTAD5ukQ6hnwdm5QEIWBYHEIl',  // DSC_7952.JPG
  'https://lh3.googleusercontent.com/d/1oSYY_Prm4sgcwtimJZ5wXmgQak0mF45u',  // DSC_7953.JPG
  'https://lh3.googleusercontent.com/d/1smWsxJ2prcaZ2BTj3Plc7v7i-w7e_2zG',  // DSC_7954.JPG
  'https://lh3.googleusercontent.com/d/1QIHjk2QEbeaw5FtLMMGYP5X3X7wmDCqX',  // DSC_7955.JPG
  'https://lh3.googleusercontent.com/d/1WhVkgyjQT1EwMiayXW01SWKVzFsY__L9',  // DSC_7956.JPG
  'https://lh3.googleusercontent.com/d/1_fF5EeEsfMoYlLE3hGvlhYZKAVuoQXRe',  // DSC_7958.JPG
  'https://lh3.googleusercontent.com/d/1eHnh95w0F4aONQv-SFxHheKZif3eGmwd',  // DSC_7959.JPG
  'https://lh3.googleusercontent.com/d/1rIIqtkG_yTE1neW1WqbraGa9byKR5Jlk',  // DSC_7960.JPG
  'https://lh3.googleusercontent.com/d/1xrnK14ra-zqI8hnj6Bu9R-gHZqDbU0MF',  // DSC_7961.JPG
  'https://lh3.googleusercontent.com/d/1fusWui3OR9L8WgxSx54t8QPe9CAi7zEt',  // DSC_7962.JPG
  'https://lh3.googleusercontent.com/d/1Xp4ygpWooZN-X5IV7Q-rcVZpMcM9kbh2',  // DSC_7963.JPG
  'https://lh3.googleusercontent.com/d/1CKUGcm3IRuo0PmvkOpTt22zEY09GIleh',  // DSC_7964.JPG
  'https://lh3.googleusercontent.com/d/1BADtc0MjvJzX2h-RfvkB026ZuSPkuHZ0',  // DSC_7965.JPG
  'https://lh3.googleusercontent.com/d/1i27X1YtuDwTE860RNkslooPN8CVcG4Na',  // DSC_7966.JPG
  'https://lh3.googleusercontent.com/d/1NQiYXCVAVsApVTgNZVy9VAOzWkt2VGgL',  // DSC_7967.JPG
  'https://lh3.googleusercontent.com/d/1Pj3R_L44My5MSmrYjCLtrI-bRjsuuyxm',  // DSC_7968.JPG
  'https://lh3.googleusercontent.com/d/1nNWFluPnfMVpGkEmZr5iUkDMxgaOXTJo',  // DSC_7969.JPG
  'https://lh3.googleusercontent.com/d/1A8DOTtzn6m28THGwh2Sb2RHkDWd60YES',  // DSC_7970.JPG
  'https://lh3.googleusercontent.com/d/1aUS68H4dqxJvw7AH5_QcniTL18dy6VRV',  // DSC_7971.JPG
  'https://lh3.googleusercontent.com/d/1uERQHgCUHhhAwAhGLqqwbqrTh8x8JrSl',  // DSC_7972.JPG
  'https://lh3.googleusercontent.com/d/1wONgWcss2NiQC3EYBIWOdXq0RdUlKqcJ',  // DSC_7973.JPG
  'https://lh3.googleusercontent.com/d/1OdeG3K95WPuR9v96CfvoipuL8MLYblYs',  // DSC_7974.JPG
  'https://lh3.googleusercontent.com/d/1ewdDGAByrS1-TaMXkZ1ty2q5DXMW3K02',  // DSC_7975.JPG
  'https://lh3.googleusercontent.com/d/1Ag22NksACSHEsSi9yY0yRJb6o7_EnzSS',  // DSC_7976.JPG
  'https://lh3.googleusercontent.com/d/19R0UGLZZxgzccsz6adx_FFxMZdiVhDVB',  // DSC_7977.JPG
  'https://lh3.googleusercontent.com/d/13LBmX1ENvOZlo5IBkN7nf-5USMS48P50',  // DSC_7978.JPG
  'https://lh3.googleusercontent.com/d/1uROgIiQZOfCq_gWi3c5tpBZ2VDoSdu8b',  // DSC_7979.JPG
  'https://lh3.googleusercontent.com/d/1cRirB0qUnptDekUlb3bdK_aPuT0ulTwc',  // DSC_7980.JPG
  'https://lh3.googleusercontent.com/d/1r6bDfID1vzY0UhQ2PnwyVAFO0Bx1-38O',  // DSC_7981.JPG
  'https://lh3.googleusercontent.com/d/1_5owgfJ9YLbAmjFzqtSoKmZS8VI7x7ha',  // DSC_7982.JPG
  'https://lh3.googleusercontent.com/d/1sVEJUlcbIuYWG8NGTQCY__6w26qUI-a6',  // DSC_7983.JPG
  'https://lh3.googleusercontent.com/d/1mq3m95ceUaZdW9-QkzeoTj70oyPlxsbq',  // DSC_7984.JPG
  'https://lh3.googleusercontent.com/d/1JTKqhjD9OSGnk3bW7l2C6n9GuaWBwqqb',  // DSC_7985.JPG
  'https://lh3.googleusercontent.com/d/1tWaMdFznWUO8GxpWoXaT_DYsjrCpeoYC',  // DSC_7986.JPG
  'https://lh3.googleusercontent.com/d/13hbdFZbhOYuzl-C8hjytNNzDKRZbmnBH',  // DSC_7988.JPG
  'https://lh3.googleusercontent.com/d/1rZsVSTVvL_YFoK-5IWAqXCSVuVB4f7i7',  // DSC_7989.JPG
  'https://lh3.googleusercontent.com/d/1982duIB9lVk5HWCqxjpvRDcz95-PrsFC',  // DSC_7990.JPG
  'https://lh3.googleusercontent.com/d/1qIaewI47fRoBK54TgJxZYRVEDSW06Ufg',  // DSC_7992.JPG
  'https://lh3.googleusercontent.com/d/1iVeZR_NLfnuM_hkDX3sMXSjeRdGYuVr0',  // DSC_7993.JPG
  'https://lh3.googleusercontent.com/d/1ITKHlmHL1pPirh2-KT8SD7Z56tHXIG94',  // DSC_7994.JPG
  'https://lh3.googleusercontent.com/d/1WDgjYAhFFFNAeI0OxGsxVouKmxlTosZ1',  // DSC_7995.JPG
  'https://lh3.googleusercontent.com/d/1LIH1vVuJPsToWbe9zvxiMSv51e8R909U',  // DSC_7996.JPG
  'https://lh3.googleusercontent.com/d/1dzcBzMB3Ee52D9JXOFqy1Urk6jSC_Qr6',  // DSC_7997.JPG
  'https://lh3.googleusercontent.com/d/1tN1VmY-pywa20Rd5Kt-NcbzOar3vxfvm',  // DSC_7998.JPG
  'https://lh3.googleusercontent.com/d/1CGWOV-qbGgsc2TyNviBgfAnkaJj0JEbE',  // DSC_7999.JPG
  'https://lh3.googleusercontent.com/d/1D3kUMf4hspsbOjshniSOVTPxL20JnCq-',  // DSC_8000.JPG
  'https://lh3.googleusercontent.com/d/1M7K_KC33hEOfXdACfH2o_ib-jPAhmXVp',  // DSC_8001.JPG
  'https://lh3.googleusercontent.com/d/1t7pk71sbkok8d8iFrp6oEAeqbwjQ2EoQ',  // DSC_8002.JPG
  'https://lh3.googleusercontent.com/d/1Ne661PBV4kmHnL32xmazGk14maNKZ0mz',  // DSC_8003.JPG
  'https://lh3.googleusercontent.com/d/1tSeJhwg_u18JAlPwlHdUSiOHM4x0AccD',  // DSC_8004.JPG
  'https://lh3.googleusercontent.com/d/1yKKgL1clLbDzZBHuMyooKkB7WTukWSh9',  // DSC_8005.JPG
  'https://lh3.googleusercontent.com/d/1drHudygCK6MYp-xzGjY5Hv6Sx4Uz8FCu',  // DSC_8006.JPG
  'https://lh3.googleusercontent.com/d/1WPoReUZmrs6gVh0p8H8fB519B8FprYd9',  // DSC_8007.JPG
  'https://lh3.googleusercontent.com/d/1KsekOjbHEosYujOQ_w2hPSqP3gO6r9zO',  // DSC_8009.JPG
  'https://lh3.googleusercontent.com/d/1Aq2sRqO1P0KzF_TJTPz2Fkr8i3ooHNq7',  // DSC_8010.JPG
  'https://lh3.googleusercontent.com/d/1A7rePjk6ANb1SheozoPrnRM_A-zC36gY',  // DSC_8011.JPG
  'https://lh3.googleusercontent.com/d/13CGOUFvtM_TGRMLKN5fI3gBmC0Wf8laq',  // DSC_8012.JPG
  'https://lh3.googleusercontent.com/d/15RUbQa8zt6quSoq0qO23VP9uPVSfAT8c',  // DSC_8013.JPG
  'https://lh3.googleusercontent.com/d/182Qgtl3T-Y8aMmIgUX5kxTKiAaIC1Vmn',  // DSC_8015.JPG
  'https://lh3.googleusercontent.com/d/1RStRGpsX8BBVQed2xUc3NlzHFpv9Eh96',  // DSC_8016.JPG
  'https://lh3.googleusercontent.com/d/1p3dB2MzIQdQ2aNyk-_Ho9YsnVvfv3evg',  // DSC_8017.JPG
  'https://lh3.googleusercontent.com/d/1hcdCkeL_RSZXBbv4VS-HsusPN1pXklbo',  // DSC_8018.JPG
  'https://lh3.googleusercontent.com/d/1GOL4ilS8WEaRzmvUkvWiw56lFDfCiNfn',  // DSC_8019.JPG
  'https://lh3.googleusercontent.com/d/1XT7Qs7VgJKS8CvvELVIlV9dgVvD_Uf_u',  // DSC_8020.JPG
  'https://lh3.googleusercontent.com/d/1ELHl3GtJ7rNmrzUB7_f-3qEKPpptxMGa',  // DSC_8021.JPG
  'https://lh3.googleusercontent.com/d/1F1rTXXa3T9iJuBT7r1K1GbwT910wrxFF',  // DSC_8022.JPG
  'https://lh3.googleusercontent.com/d/19Gtbb6k2QWjtrpg7dYvIBf7vQTrsqdxF',  // DSC_8023.JPG
  'https://lh3.googleusercontent.com/d/15FIbOIGvUpkq7SHXcb7YzdFbhhEb1ANu',  // DSC_8024.JPG
  'https://lh3.googleusercontent.com/d/1g-rjH0QH6QDI_kRe9CCjTEYeACX-QVIT',  // DSC_8025.JPG
  'https://lh3.googleusercontent.com/d/1N212qz7Emx6koWi9gF3109rYN2ooKsQE',  // DSC_8027.JPG
  'https://lh3.googleusercontent.com/d/1p_oFKH-xzP_zWqqAr_wP_mL5bJFiJkYm',  // DSC_8028.JPG
  'https://lh3.googleusercontent.com/d/1BLEUD88vuDzUYk64HuNWzts2AUou1geU',  // DSC_8029.JPG
  'https://lh3.googleusercontent.com/d/1IHJVGpL3sQrVoymCGP5Y2HOqgF0_02ck',  // DSC_8030.JPG
  'https://lh3.googleusercontent.com/d/1SN_Htq-sLJ1-QRSCdLp9VnMawa62YrM_',  // DSC_8031.JPG
  'https://lh3.googleusercontent.com/d/1L4vXuU_W-aS30Ihh_26yH3BhyiHbrmDO',  // DSC_8032.JPG
  'https://lh3.googleusercontent.com/d/1K5ieFnAFWlmfmGNRNM6ERLoVnWUqZNlE',  // DSC_8033.JPG
  'https://lh3.googleusercontent.com/d/1ZTLhgMbxOTPT3Ow6DPPA_MSZa_vqe45N',  // DSC_8034.JPG
  'https://lh3.googleusercontent.com/d/1BUYr2yLkP7RrohLz53qZVmjgdwQGOHLq',  // DSC_8035.JPG
  'https://lh3.googleusercontent.com/d/1sdwRipu_z2G-jKHAISYv4N40L42vK9dQ',  // DSC_8036.JPG
  'https://lh3.googleusercontent.com/d/1CUvZthTTIqihZYdX7A6ip2SJlBEsVHsn',  // DSC_8037.JPG
  'https://lh3.googleusercontent.com/d/1ykA9HS7up_rgzgMenxzosvkXT6UZ4jWs',  // DSC_8038.JPG
  'https://lh3.googleusercontent.com/d/1-SsAbf36pL_y9vorEJZVdQKZimZSKdMm',  // DSC_8039.JPG
  'https://lh3.googleusercontent.com/d/1pdezxk9hECTHZvgINQ7rZTQsUCDGdaYV',  // DSC_8040.JPG
  'https://lh3.googleusercontent.com/d/1Rz-U1jbB01hh83YBJop5VICveX8U3zIP',  // DSC_8041.JPG
  'https://lh3.googleusercontent.com/d/11bQaltb234Z7-9nuwGzITT5eM41m4dKM',  // DSC_8042.JPG
  'https://lh3.googleusercontent.com/d/1LOYfAfZuS42K6L1IevxCFFOcL07xEbqk',  // DSC_8043.JPG
  'https://lh3.googleusercontent.com/d/1Ljo0i2n27GWYfQn-LAYyuS1hgF3qG67Q',  // DSC_8044.JPG
  'https://lh3.googleusercontent.com/d/1MREkDzmN_dkvCBjZonI9zyn_dSwauv29',  // DSC_8045.JPG
  'https://lh3.googleusercontent.com/d/1efN5u1Tj6AwUq7wO8U-MDSgtoB1O_Jfo',  // DSC_8046.JPG
  'https://lh3.googleusercontent.com/d/1XYb_KXnLwxVR_GZX_Ozwwy7W8uwPpJgW',  // DSC_8047.JPG
  'https://lh3.googleusercontent.com/d/1bkNz8kgpRIS1rP5-qtKPyWOrcTuJMyLx',  // DSC_8048.JPG
  'https://lh3.googleusercontent.com/d/1sjjtfPrKKwxP_asOV5wOJKdAkV300CQV',  // DSC_8049.JPG
  'https://lh3.googleusercontent.com/d/1RZcYkPzooUKRJoizEWfPZaX9EmSc3dgH',  // DSC_8050.JPG
  'https://lh3.googleusercontent.com/d/1shRDjZbWAX3VTj05FaN-t-Ir6nnGqu7a',  // DSC_8051.JPG
  'https://lh3.googleusercontent.com/d/1NAd0lu6qXy3p8rgg118ZTZjKFJTQ-9JP',  // DSC_8052.JPG
  'https://lh3.googleusercontent.com/d/1SJDOSlICWMCQfUHUb7NZcfvwGInBjsIO',  // DSC_8053.JPG
  'https://lh3.googleusercontent.com/d/1j5ebXE6TleJqeVtFm3vvsFGKyxua0ZBN',  // DSC_8055.JPG
  'https://lh3.googleusercontent.com/d/13LD2DDWNU-7V12Am8JffmBmNhJuvG8Gq',  // DSC_8056.JPG
  'https://lh3.googleusercontent.com/d/1IUjOvRoUuGwQ5yhj9mdfRaz3EX0LPwrI',  // DSC_8057.JPG
  'https://lh3.googleusercontent.com/d/1gYrPM_6J0kNqRbF1QNjlH_Bt1bLYVcQ5',  // DSC_8059.JPG
  'https://lh3.googleusercontent.com/d/1Ywo1TEcOlugr_viOkRmijpS57dO7tKOQ',  // DSC_8060.JPG
  'https://lh3.googleusercontent.com/d/1nLMlyxJ3FJnnZmHDCDIG_i7SFJdwhLOE',  // DSC_8061.JPG
  'https://lh3.googleusercontent.com/d/1f9dw6GDplYgWTO30v1kMebzMg8gvOUBa',  // DSC_8062.JPG
  'https://lh3.googleusercontent.com/d/1jSEqfUXq-SxhJ8aavMOx92wbCEmrx2Fs',  // DSC_8063.JPG
  'https://lh3.googleusercontent.com/d/13RM1BVhLMU8PkRUtz-ZpwNM9m8j7Ndmm',  // DSC_8064.JPG
  'https://lh3.googleusercontent.com/d/12Sg1xv6sIHe6iqqH-6awOk-iHTpYdJin',  // DSC_8065.JPG
  'https://lh3.googleusercontent.com/d/1vtCKXNgtT4feCyCxBbJ1PFogYWwpsPUJ',  // DSC_8066.JPG
  'https://lh3.googleusercontent.com/d/1-Vm1902T8_zTTND1jD3xXcMQ0Uaz2gSz',  // DSC_8067.JPG
  'https://lh3.googleusercontent.com/d/11QVhfvJMXDaeWwMIrmxbw6SdrYWsA-px',  // DSC_8068.JPG
  'https://lh3.googleusercontent.com/d/1nuSlcMstWSAui8p157gS6YZ2v2cQ9S4s',  // DSC_8069.JPG
  'https://lh3.googleusercontent.com/d/1mogwMbhLGH7vQx_h7TV_bgT1pLPgQAK-',  // DSC_8070.JPG
  'https://lh3.googleusercontent.com/d/1u2eFzWE6L0EmO-Z2YvOVqm6lS2xZCS4I',  // DSC_8071.JPG
  'https://lh3.googleusercontent.com/d/1rn0lxy29SG9IP2iub1QYpXKVlgCOVwFp',  // DSC_8072.JPG
  'https://lh3.googleusercontent.com/d/1euhStwBOdWzN-RAUID21tbnBxEvaOauN',  // DSC_8073.JPG
  'https://lh3.googleusercontent.com/d/11Z600k_Na1C_JlDEmJYh6nAmFIVGH3st',  // DSC_8074.JPG
  'https://lh3.googleusercontent.com/d/1fRb8IbjHayLduEgGt6IocydSFK-0DxXS',  // DSC_8075.JPG
  'https://lh3.googleusercontent.com/d/1Srr6mMbn4zw0wTXKA5BsED6La7Kq8-01',  // DSC_8076.JPG
  'https://lh3.googleusercontent.com/d/1mH_-InVKTFMTB9KEq7UOn4Gm7Dyr8PST',  // DSC_8077.JPG
  'https://lh3.googleusercontent.com/d/1UiD2m7B6lV7BbuQnDQlEHvMmCq4CfS-c',  // DSC_8078.JPG
  'https://lh3.googleusercontent.com/d/16soyaMrXD0iQY8RFCvIzR6M9kU_3Hmc-',  // DSC_8079.JPG
  'https://lh3.googleusercontent.com/d/1udInoV_Oz3dV8LCMAvfZ2QvbQNn1gLHI',  // DSC_8080.JPG
  'https://lh3.googleusercontent.com/d/1O7_5P8nvPYC33213fEIRtiY4RIDC2Kfv',  // DSC_8081.JPG
  'https://lh3.googleusercontent.com/d/1eC8qErsVRTROihh3djNdpf4_VIqZn-YS',  // DSC_8082.JPG
  'https://lh3.googleusercontent.com/d/1Q15DhFWHRjEbR0yypEfpSC0d7OQcYalt',  // DSC_8083.JPG
  'https://lh3.googleusercontent.com/d/11qbJGuqQAYEG_qZSyjDiKWYcZzJh_wpk',  // DSC_8084.JPG
  'https://lh3.googleusercontent.com/d/1AntKr7ZLuHqN-4KNjB0IET_PpNqcbTd_',  // DSC_8085.JPG
  'https://lh3.googleusercontent.com/d/1VAgoif9HTf0nbaPtJHJKXuBighZdUsz_',  // DSC_8086.JPG
  'https://lh3.googleusercontent.com/d/1yN656NMwyZa4xCw-XYLzH3rNcUteMWAh',  // DSC_8087.JPG
  'https://lh3.googleusercontent.com/d/18kIgeTAfsGwOY4zqfh9p1m0wmgGKVcK8',  // DSC_8088.JPG
  'https://lh3.googleusercontent.com/d/14MtlXJdosCgjJJX_Qfp6k2L7a3VObnJ5',  // DSC_8089.JPG
  'https://lh3.googleusercontent.com/d/1LvTbvO7qR0TPq34pNM7rkl6D1ekYMbQ0',  // DSC_8090.JPG
  'https://lh3.googleusercontent.com/d/1xFV_tfX199tePZp-c8RBRqF4wQzLyPxO',  // DSC_8091.JPG
  'https://lh3.googleusercontent.com/d/1WQ8F3SiZZQRjdcvWDzVpKacLRvoQSweo',  // DSC_8092.JPG
  'https://lh3.googleusercontent.com/d/1lHLquZkLemyUoczFVOz1ihnyEnwU5OFZ',  // DSC_8093.JPG
  'https://lh3.googleusercontent.com/d/1XH3b_z1t70O1aSnJm93ncTH9SgjqwyV5',  // DSC_8094.JPG
  'https://lh3.googleusercontent.com/d/1AxeFKsCEPAYfV-6YuPbXhXPC8pCWq5u_',  // DSC_8095.JPG
  'https://lh3.googleusercontent.com/d/17i6XsnxWv9ZxjkCUz0a9bcZxGgTTwvSu',  // DSC_8096.JPG
  'https://lh3.googleusercontent.com/d/1PTkqNak_IVIOcpBlp-KHWEnVFJk6nmj3',  // DSC_8097.JPG
  'https://lh3.googleusercontent.com/d/1HrL7B7iKdpcLFKMLbE6GVCA7gZxkeWvd',  // DSC_8098.JPG
  'https://lh3.googleusercontent.com/d/1Blqxrb2K6h2TB2GvWKKZr9TF8JcpvFzN',  // DSC_8100.JPG
  'https://lh3.googleusercontent.com/d/1W7vwTz-PK24m-0nYR0xUttFwDDYphzGx',  // DSC_8101.JPG
  'https://lh3.googleusercontent.com/d/1uzbgoTIyNDl6Zr_CfxnxEOGxPtXld7RH',  // DSC_8102.JPG
  'https://lh3.googleusercontent.com/d/150lbORfFPGvqnh7T4tWdtQdDGVRfS5lG',  // DSC_8103.JPG
  'https://lh3.googleusercontent.com/d/18GpgRcb1o8t3ni1RAs3-8Fc4KJWkQZsr',  // DSC_8104.JPG
  'https://lh3.googleusercontent.com/d/1VnH7CKJkWnWgZ-jd-pIrag180c5inCEH',  // DSC_8105.JPG
  'https://lh3.googleusercontent.com/d/1qTkZunkCkkg_In44cm2DOGB98jdcwxzK',  // DSC_8106.JPG
  'https://lh3.googleusercontent.com/d/1DcmlHg8ivWzoG5l2fNNA2x8VCWj9vlyN',  // DSC_8107.JPG
  'https://lh3.googleusercontent.com/d/1cs6OgQO7F3bakQL8Tdb6nqNKGLiL_f2V',  // DSC_8108.JPG
  'https://lh3.googleusercontent.com/d/19XaxEQdXW_jaT6PJH93wYRD_Z-GilRRz',  // DSC_8109.JPG
  'https://lh3.googleusercontent.com/d/11l8GSjiDrLIaxKNETk_IwNUQunSma7xH',  // DSC_8110.JPG
  'https://lh3.googleusercontent.com/d/1W24Lghr9bQlj9iB105Y9UD8_6kyDO57H',  // DSC_8111.JPG
  'https://lh3.googleusercontent.com/d/1jWfyDFWTRGMQ_UAsxwhlc7MjoLK6Zatt',  // DSC_8112.JPG
  'https://lh3.googleusercontent.com/d/1M_pfMVgSRvqxLhcY7WfJhU_qhvYwISuY',  // DSC_8113.JPG
  'https://lh3.googleusercontent.com/d/1FGE_MZ2tQ2ALK7NeOEZzV-uYNCldACyT',  // DSC_8114.JPG
  'https://lh3.googleusercontent.com/d/1ZuARZG5lF1YMbA-edS-8I8iw5Z1wP8PT',  // DSC_8115.JPG
  'https://lh3.googleusercontent.com/d/1iP952CUv8pXHeb4AkizF0JitvPwqbPR3',  // DSC_8116.JPG
  'https://lh3.googleusercontent.com/d/1xlXYKYabiwjVNXewXTnenGa1W0MGW0yW',  // DSC_8117.JPG
  'https://lh3.googleusercontent.com/d/1db5nvcFa3Hj9U6PpdO2dEE216kYKouxz',  // DSC_8118.JPG
  'https://lh3.googleusercontent.com/d/1I2PK8G01Yx-O2ue6duESDfClwwllFZ0F',  // DSC_8119.JPG
  'https://lh3.googleusercontent.com/d/1CRCvb-YdayQCcOBM9zZPTVbpp3na3AKF',  // DSC_8120.JPG
  'https://lh3.googleusercontent.com/d/1667prCdsZni1tD7viBV5tfiPz8Bs8abL',  // DSC_8121.JPG
  'https://lh3.googleusercontent.com/d/1Dx85fcRzcPgos_Mu9DbP5ogOaDA8LOBC',  // DSC_8122.JPG
  'https://lh3.googleusercontent.com/d/1w4bTE06WMVK8unJcNvN0ROHUquP2Nat0',  // DSC_8123.JPG
  'https://lh3.googleusercontent.com/d/1clLa6xV1UXhpafHry3HTvhu_mbMGURc4',  // DSC_8125.JPG
  'https://lh3.googleusercontent.com/d/1pFkM8lfMK5H47XrCU0F9lUhwhS93CY47',  // DSC_8126.JPG
  'https://lh3.googleusercontent.com/d/1k5x6aZOKH6ry4JzNJpi0XGkHhO5x0yaF',  // DSC_8127.JPG
  'https://lh3.googleusercontent.com/d/1fnK0k1AdBW4AEzifBlL_V8fkVHUnuJCt',  // DSC_8128.JPG
  'https://lh3.googleusercontent.com/d/1ct3nxYid0IEu5vCsmANmNw7lRRgZtxWc',  // DSC_8129.JPG
  'https://lh3.googleusercontent.com/d/1bjwyHvFEbMCB06OZySj4UNzNn3fTSV4t',  // DSC_8130.JPG
  'https://lh3.googleusercontent.com/d/1jhjhSzKCt-HKzEQwnmirKGOxU0CIoX1G',  // DSC_8131.JPG
  'https://lh3.googleusercontent.com/d/15S7jZ9CpHkIYUd7JnB4lPX-7rbLvfeBL',  // DSC_8132.JPG
  'https://lh3.googleusercontent.com/d/1yVXh5jKqBFs9YQRVknFCs8HWIoS-F3JG',  // DSC_8133.JPG
  'https://lh3.googleusercontent.com/d/1lyCPVSLaxSLxZe-fB0An5-BNOgmt_MMb',  // DSC_8134.JPG
];

const BATCH   = 30;
let shown     = 0;

const grid    = document.getElementById('galleryGrid');
const countEl = document.getElementById('galleryCount');
const btnMore = document.getElementById('btnLoadMore');
const btnAll  = document.getElementById('btnLoadAll');

// ── Column management ─────────────────────────────────────────────────
let colEls  = [];
let nextCol = 0;

function getColCount() {
  const w = window.innerWidth;
  if (w >= 1200) return 4;
  if (w >= 900)  return 3;
  if (w >= 600)  return 2;
  return 1;
}

function initGrid() {
  grid.innerHTML = '';
  colEls  = [];
  nextCol = 0;
  const n = getColCount();
  for (let i = 0; i < n; i++) {
    const col = document.createElement('div');
    col.className = 'gallery-col';
    grid.appendChild(col);
    colEls.push(col);
  }
}

function updateCount() {
  countEl.textContent = `Showing ${shown} of ${images.length} photos`;
  btnMore.disabled = shown >= images.length;
  btnAll.disabled  = shown >= images.length;
}

function addItems(start, end) {
  for (let i = start; i < end && i < images.length; i++) {
    const item = document.createElement('div');
    item.className = 'gallery-item';

    const img = document.createElement('img');
    img.src      = images[i];
    img.alt      = `Engagement photo ${i + 1}`;
    img.loading  = 'lazy';
    img.decoding = 'async';
    img.onload  = () => img.classList.add('loaded');
    img.onerror = () => img.classList.add('loaded');

    const overlay = document.createElement('div');
    overlay.className = 'item-overlay';
    overlay.innerHTML = '<span class="zoom-icon">⊕</span>';

    item.appendChild(img);
    item.appendChild(overlay);
    addMehndiCorners(item);
    item.addEventListener('click', () => openLightbox(i));
    colEls[nextCol % colEls.length].appendChild(item);
    nextCol++;
  }
}

function loadMore() {
  const next = Math.min(shown + BATCH, images.length);
  addItems(shown, next);
  shown = next;
  updateCount();
}

function loadAll() {
  addItems(shown, images.length);
  shown = images.length;
  updateCount();
}

btnMore.addEventListener('click', loadMore);
btnAll.addEventListener('click', loadAll);
initGrid();
loadMore();

// ── Lightbox ──────────────────────────────────────────────────────────
const lightbox      = document.getElementById('lightbox');
const lbImg         = document.getElementById('lb-img');
const lbCounter     = document.getElementById('lb-counter');
const lbClose       = document.getElementById('lb-close');
const lbPrev        = document.getElementById('lb-prev');
const lbNext        = document.getElementById('lb-next');
const lbPlay        = document.getElementById('lb-play');
const lbProgressBar = document.getElementById('lb-progress-bar');
let currentIdx      = 0;

function openLightbox(idx) {
  currentIdx = idx;
  setLbImage(idx);
  lightbox.classList.add('active');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  stopSlideshow();
  resetZoom();
  lightbox.classList.remove('active');
  document.body.style.overflow = '';
}

function setLbImage(idx) {
  lbImg.classList.add('loading');
  const tmp = new Image();
  tmp.onload = () => { lbImg.src = tmp.src; lbImg.classList.remove('loading'); };
  tmp.src = images[idx];
  lbCounter.textContent = `${idx + 1} / ${images.length}`;
}

function lbGo(dir) {
  resetZoom();
  currentIdx = (currentIdx + dir + images.length) % images.length;
  setLbImage(currentIdx);
  if (slideshowActive) restartProgress();
}

lbClose.addEventListener('click', closeLightbox);
lbPrev.addEventListener('click', () => lbGo(-1));
lbNext.addEventListener('click', () => lbGo(1));
lightbox.addEventListener('click', (e) => { if (e.target === lightbox) closeLightbox(); });
document.addEventListener('keydown', (e) => {
  if (!lightbox.classList.contains('active')) return;
  if (e.key === 'Escape')     closeLightbox();
  if (e.key === 'ArrowLeft')  lbGo(-1);
  if (e.key === 'ArrowRight') lbGo(1);
  if (e.key === ' ')          toggleSlideshow();
});

// ── Slideshow ─────────────────────────────────────────────────────────
const SLIDESHOW_MS  = 3500;
let slideshowActive = false;
let slideshowTimer  = null;

function startSlideshow() {
  slideshowActive = true;
  lbPlay.classList.add('playing');
  lbPlay.innerHTML = '&#9646;&#9646;';
  lbPlay.setAttribute('aria-label', 'Pause slideshow');
  restartProgress();
}

function stopSlideshow() {
  slideshowActive = false;
  clearTimeout(slideshowTimer);
  lbPlay.classList.remove('playing');
  lbPlay.innerHTML = '&#9654;';
  lbPlay.setAttribute('aria-label', 'Play slideshow');
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
}

function toggleSlideshow() { slideshowActive ? stopSlideshow() : startSlideshow(); }

function restartProgress() {
  clearTimeout(slideshowTimer);
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
  void lbProgressBar.offsetWidth;
  lbProgressBar.style.transition = `width ${SLIDESHOW_MS}ms linear`;
  lbProgressBar.style.width = '100%';
  slideshowTimer = setTimeout(() => { if (slideshowActive) lbGo(1); }, SLIDESHOW_MS);
}

lbPlay.addEventListener('click', toggleSlideshow);

// ── Pinch-to-Zoom & Pan ───────────────────────────────────────────────
let scale = 1, panX = 0, panY = 0;
let isPinching = false, initDist = 0, initScale = 1;
let isDragging = false, dragStartX = 0, dragStartY = 0, dragPanX = 0, dragPanY = 0;
let lastTap = 0;

function applyTransform(animated) {
  if (animated) { lbImg.style.transition = 'transform 0.25s ease'; setTimeout(() => { lbImg.style.transition = ''; }, 260); }
  else { lbImg.style.transition = ''; }
  lbImg.style.transform = `translate(${panX}px, ${panY}px) scale(${scale})`;
  lbImg.classList.toggle('zoomed', scale > 1);
}

function resetZoom() {
  scale = 1; panX = 0; panY = 0;
  lbImg.style.transition = 'transform 0.25s ease';
  lbImg.style.transform = '';
  lbImg.classList.remove('zoomed', 'dragging');
  setTimeout(() => { lbImg.style.transition = ''; }, 260);
}

function getDist(t) { return Math.hypot(t[0].clientX - t[1].clientX, t[0].clientY - t[1].clientY); }

lbImg.addEventListener('touchstart', (e) => {
  if (e.touches.length === 2) {
    isPinching = true; isDragging = false;
    initDist = getDist(e.touches); initScale = scale; e.preventDefault();
  } else if (e.touches.length === 1) {
    const now = Date.now();
    if (now - lastTap < 280) { lastTap = 0; scale > 1 ? resetZoom() : (scale = 2.5, applyTransform(true)); e.preventDefault(); return; }
    lastTap = now;
    if (scale > 1) { isDragging = true; dragStartX = e.touches[0].clientX; dragStartY = e.touches[0].clientY; dragPanX = panX; dragPanY = panY; lbImg.classList.add('dragging'); e.preventDefault(); }
  }
}, { passive: false });

lbImg.addEventListener('touchmove', (e) => {
  if (isPinching && e.touches.length === 2) { scale = Math.min(Math.max(initScale * (getDist(e.touches) / initDist), 1), 4); applyTransform(false); e.preventDefault(); }
  else if (isDragging && e.touches.length === 1 && scale > 1) { panX = dragPanX + (e.touches[0].clientX - dragStartX); panY = dragPanY + (e.touches[0].clientY - dragStartY); applyTransform(false); e.preventDefault(); }
}, { passive: false });

lbImg.addEventListener('touchend', (e) => {
  if (e.touches.length < 2) isPinching = false;
  if (e.touches.length === 0) { isDragging = false; lbImg.classList.remove('dragging'); if (scale < 1.08) resetZoom(); }
});

let swipeStartX = 0, swipeStartY = 0;
lightbox.addEventListener('touchstart', (e) => { if (e.target === lbImg) return; swipeStartX = e.touches[0].clientX; swipeStartY = e.touches[0].clientY; }, { passive: true });
lightbox.addEventListener('touchend', (e) => {
  if (e.target === lbImg || scale > 1) return;
  const dx = e.changedTouches[0].clientX - swipeStartX;
  const dy = e.changedTouches[0].clientY - swipeStartY;
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) lbGo(dx < 0 ? 1 : -1);
});
