// ── All Matkor Images ─────────────────────────────────────────────────
// Auto-generated by tools/get-drive-images.js  (2026-03-24)
// Source folder: MATKOR  (116 images)
const images = [
  'https://lh3.googleusercontent.com/d/1Bk1IkebNxO9yZX3v4A2-BVYjbiiXr5F0',  // _DSC1927.JPG
  'https://lh3.googleusercontent.com/d/1OW3rC2JARQNvNrPbCDgjB2wTKF-CSdsd',  // _DSC1928.JPG
  'https://lh3.googleusercontent.com/d/1Oz-fzKQMLJcguxdgUa0IpHv6BrB6b_9X',  // _DSC1930.JPG
  'https://lh3.googleusercontent.com/d/1bym4pqK9UmYRgQW2TOfG1z4M7GT2AZBY',  // _DSC1931.JPG
  'https://lh3.googleusercontent.com/d/1JGkYhqBtmE-zQWLT-D0KRtTkdELOeFe7',  // _DSC1935.JPG
  'https://lh3.googleusercontent.com/d/1XkjM4ciA4dt9SZirmdN9Y-FuurYxZvgs',  // _DSC1936.JPG
  'https://lh3.googleusercontent.com/d/1IGIUG7JLEXJKI0jyCos7t3VeYcFt7w9j',  // _DSC1938.JPG
  'https://lh3.googleusercontent.com/d/10VB5oh2iIIeZb-MtrPO1KbbyBHorTM_B',  // _DSC1939.JPG
  'https://lh3.googleusercontent.com/d/1nQKt0a_SSfF6ze3gyoNsNkpo91RRK3V3',  // _DSC1940.JPG
  'https://lh3.googleusercontent.com/d/1C2KJ7s8ZiGfN-GYDoFS916VyiyXK3jVy',  // _DSC1942.JPG
  'https://lh3.googleusercontent.com/d/13P7zlnOfnHS9P1Mm72GuA28fZuUcudXR',  // _DSC1944.JPG
  'https://lh3.googleusercontent.com/d/1ldXZWKM1wrFHyDmPCHCTpP1Hb4rQOxJg',  // _DSC1948.JPG
  'https://lh3.googleusercontent.com/d/1e8FRWNs4Als9xJ0oK-rUpxWm6AJd3rQS',  // _DSC1949.JPG
  'https://lh3.googleusercontent.com/d/1Z7-YAUSdz-o_yvTK2ahsvPQ8dqBrLfjZ',  // _DSC1950.JPG
  'https://lh3.googleusercontent.com/d/1ElReA4o2RKAHH_ii-zagsQQKDNVynJ8E',  // _DSC1952.JPG
  'https://lh3.googleusercontent.com/d/1osr8EHi3ZGzauK3V7Op-Jm2qIHgSa75_',  // _DSC1955.JPG
  'https://lh3.googleusercontent.com/d/1flZVvA9hHVojKJt4PDT5Ek_F_iUhZzFU',  // _DSC1957.JPG
  'https://lh3.googleusercontent.com/d/1_em6sJCIRMOMa4S5Y--hMX2jZ74EZTWU',  // _DSC1962.JPG
  'https://lh3.googleusercontent.com/d/1_KBw2N34_ig_zmq5mzXPimtxTIEz_9o9',  // _DSC1963.JPG
  'https://lh3.googleusercontent.com/d/13k18rDLSGZl7p-0OmoTDkAlHum7SsI0C',  // _DSC1964.JPG
  'https://lh3.googleusercontent.com/d/1qT6Sl_0tRxWlY-_nytF_EY6jeMkF6ICC',  // _DSC1970.JPG
  'https://lh3.googleusercontent.com/d/1oXhxN17tHxcs1fglqnO5bEB7oPj9e3IG',  // _DSC1972.JPG
  'https://lh3.googleusercontent.com/d/1b8ty2pGWRFtI8Pq05k7DhTAZaugNyiD7',  // _DSC1975.JPG
  'https://lh3.googleusercontent.com/d/1_quggv6Q5GTBGkSgMWmg-5iqflKchS8a',  // _DSC1976.JPG
  'https://lh3.googleusercontent.com/d/1J62BRxoGaK1oxnldRZvsrVpdlevX1p6G',  // _DSC1979.JPG
  'https://lh3.googleusercontent.com/d/1F9U-0mqk3qTJnd8iEQSStCOgHegWTf9q',  // _DSC1981.JPG
  'https://lh3.googleusercontent.com/d/1hObuqlS1x2R64WLoPVTRv1F-QcBRRuqa',  // _DSC1982.JPG
  'https://lh3.googleusercontent.com/d/1YoLjs_MHWvtoZNmyzWFK1OfTpKSxeBJC',  // _DSC1984.JPG
  'https://lh3.googleusercontent.com/d/1ujUQ7hJHjHeT9zcqO6j6_1F60Y28PUFu',  // _DSC1985.JPG
  'https://lh3.googleusercontent.com/d/15mC0-Qy-gUqC-US-ibPgSBacpn3-re1G',  // _DSC1988.JPG
  'https://lh3.googleusercontent.com/d/1pKbAvk03FieObZdXthCzMK4FhnUfyEBC',  // _DSC1989.JPG
  'https://lh3.googleusercontent.com/d/1xlfqDKDyV2nqwQ6xOv_kef2m2vJrZ3zB',  // _DSC1990.JPG
  'https://lh3.googleusercontent.com/d/1bxTb14TZzQ27hVsmQw0oqhTHvggKDTAw',  // _DSC1991.JPG
  'https://lh3.googleusercontent.com/d/1qWl6H5wv1ILpEbhI6nC0IIN6hLVr4JI2',  // _DSC1993.JPG
  'https://lh3.googleusercontent.com/d/1c9ho4Xt-nJm725lEZklXahdUMZYIil0n',  // _DSC1998.JPG
  'https://lh3.googleusercontent.com/d/1ZhQNgCjSneDR_uimqs-HRSboSsqliFVW',  // _DSC1999.JPG
  'https://lh3.googleusercontent.com/d/1vI9ihTGwEnU6b0qc-pwxq7tX2Sq5ge2n',  // _DSC2001.JPG
  'https://lh3.googleusercontent.com/d/1hAr4ZgX6Mm-IfwdrcEGUN6yJfP-_f79w',  // _DSC2003.JPG
  'https://lh3.googleusercontent.com/d/14GqVH2l8ojTyJjeh3syxOVxK-GCfHbfg',  // _DSC2005.JPG
  'https://lh3.googleusercontent.com/d/1afVNjDENrLTFX4WEbhNPvzeQ8MwYe-zu',  // _DSC2007.JPG
  'https://lh3.googleusercontent.com/d/1Ym3yRm1GawZ2SKHdRF9cPrTKM1vF10qf',  // _DSC2009.JPG
  'https://lh3.googleusercontent.com/d/1a8E9OHR0WLIGM0F69RmMbUEbKPDTfBzm',  // _DSC2010.JPG
  'https://lh3.googleusercontent.com/d/1BcoSg6hDcFgYGAuxLoZAY7QUzA-Ourqk',  // _DSC2013.JPG
  'https://lh3.googleusercontent.com/d/1jqUMgxgmU0ccZwkD_NTy-9AO5wbnM-pn',  // _DSC2014.JPG
  'https://lh3.googleusercontent.com/d/1_Yv9syjto2L5cZJGIV28rh3PiOlDPh1F',  // _DSC2015.JPG
  'https://lh3.googleusercontent.com/d/1acxeiSoMxOBZcFrFQVv0t2F8e2-y0fsb',  // _DSC2016.JPG
  'https://lh3.googleusercontent.com/d/1IvAyzaWRn2lzMGoSaeRVglFwZJsrsBUI',  // _DSC2017.JPG
  'https://lh3.googleusercontent.com/d/1rTGJf4qdD0J892xGoJVRB5fXCyYCzAOY',  // _DSC2018.JPG
  'https://lh3.googleusercontent.com/d/1JK2XyBgOcrh7DCIazjn2724rMvsIOyaa',  // _DSC2019.JPG
  'https://lh3.googleusercontent.com/d/1-_B0wEtwxo3PXqP71ZX-fQyfwSGhsDhZ',  // _DSC2020.JPG
  'https://lh3.googleusercontent.com/d/1E5dZngn0g2me2GYf3S32rNDpX9LQatz7',  // _DSC2022.JPG
  'https://lh3.googleusercontent.com/d/1TvRZRlvhoRTH2JGDImkqz2nbKI2LblL8',  // _DSC2025.JPG
  'https://lh3.googleusercontent.com/d/1uNcWvjD0tXuu7QeoTgnCY_jRLoAHxAaA',  // _DSC2035.JPG
  'https://lh3.googleusercontent.com/d/1cMcm09cQHfgb4W1zF9im8WfFM9i-rRc6',  // _DSC2036.JPG
  'https://lh3.googleusercontent.com/d/1eA0UxQ5bEJi3PR9_jGp7KnMhwSuRjErS',  // _DSC2038.JPG
  'https://lh3.googleusercontent.com/d/1LeVpUDoUYHE8hvSK-83y7kmFXkO6RdGp',  // _DSC2040.JPG
  'https://lh3.googleusercontent.com/d/1C4bPEy-ks_NK8CgRZoe3XW33XCiDnJU4',  // _DSC2043.JPG
  'https://lh3.googleusercontent.com/d/1lFCKh6kNmSofmzWnC5XBrOrMlHs87X9t',  // _DSC2045.JPG
  'https://lh3.googleusercontent.com/d/1gXPMw0uBj_sz1IDdzzhsqftdZuVyVO9S',  // _DSC2048.JPG
  'https://lh3.googleusercontent.com/d/1c0W6go0AHuoRoQnjS3sQo09BX4awuyl8',  // _DSC2049.JPG
  'https://lh3.googleusercontent.com/d/1COxUaCFI_JJDHA8KS0UBPtlRiZPNOu6C',  // _DSC2050.JPG
  'https://lh3.googleusercontent.com/d/1p2QBGNL27kR0OCDUCXRhnZlBqHfeFkYt',  // _DSC2051.JPG
  'https://lh3.googleusercontent.com/d/1JrGF1PFoH-PsP-JORl-t68pc1orknIjM',  // _DSC2052.JPG
  'https://lh3.googleusercontent.com/d/1lz2kMz-ddm0LeLCO-0UShKML0wV7bjv7',  // _DSC2053.JPG
  'https://lh3.googleusercontent.com/d/12t9AIUhTURsY6dReQMKPrDBwxQAlwpfU',  // _DSC2054.JPG
  'https://lh3.googleusercontent.com/d/1K5iGTLqM9-sdlOGE-PTgL4LhlkQlmRvs',  // _DSC2057.JPG
  'https://lh3.googleusercontent.com/d/1sRD7ux1EnAJZtoWqHE-gpoLXPtEFCnAU',  // _DSC2061.JPG
  'https://lh3.googleusercontent.com/d/16ztoLtYpABklZ4PFIgX6I4VLKyrJUDWV',  // _DSC2062.JPG
  'https://lh3.googleusercontent.com/d/1HJmN9dQ22FNtIplsYfvuKkKff9ypPVKQ',  // _DSC2067.JPG
  'https://lh3.googleusercontent.com/d/1S28n8g27lw_XUhv-_7PwmqOz1_ODEgmA',  // _DSC2068.JPG
  'https://lh3.googleusercontent.com/d/1Ec8YTeIOYZL-WirMenQdoBPzUj9VcHZL',  // _DSC2070.JPG
  'https://lh3.googleusercontent.com/d/14vl60ZwoBpBumx2dSCWvic292CkIlB6W',  // _DSC2073.JPG
  'https://lh3.googleusercontent.com/d/1T0kAbjLYP4tkAa5TjZ2_gYxFEPEflDXo',  // _DSC2075.JPG
  'https://lh3.googleusercontent.com/d/1J8F1djnWmbqg2t8_mujbt4u7NZxkVPSz',  // _DSC2077.JPG
  'https://lh3.googleusercontent.com/d/16_gdZQs1pKZIYFxzffPqVZ-g4msyG6e6',  // _DSC2079.JPG
  'https://lh3.googleusercontent.com/d/1xf4_DnDPg9wcpkfD0aF7Fgb4-byRfX9w',  // _DSC2081.JPG
  'https://lh3.googleusercontent.com/d/17nSYpOC4mOD6ZR5PisvbBepDAPclVSen',  // _DSC2082.JPG
  'https://lh3.googleusercontent.com/d/1mt2Wl2cPD3hRvw6GSe9-IPTD18e7QNT0',  // _DSC2084.JPG
  'https://lh3.googleusercontent.com/d/1ww1086d13I6GkxdBuoXAl0Ndtw-Ho8tW',  // _DSC2089.JPG
  'https://lh3.googleusercontent.com/d/1JjtxsNtPWRjry3NQJVHckHDhZiLtvJ23',  // _DSC2093.JPG
  'https://lh3.googleusercontent.com/d/1LfaJI1LtEALjZpdYXce-Fesdex4_5FKm',  // _DSC2095.JPG
  'https://lh3.googleusercontent.com/d/1YV2ShfhrCf2rB8mFaSzaWc09eX_hKs-M',  // _DSC2097.JPG
  'https://lh3.googleusercontent.com/d/1tjL1syzPqwQ6_JN1oiBZTJ1TcaH-gSJr',  // _DSC2098.JPG
  'https://lh3.googleusercontent.com/d/1rv_H7U5pg7YQhEos3SElSrOjcQTANrbj',  // _DSC2099.JPG
  'https://lh3.googleusercontent.com/d/17EsA82MP1G2iU8Q9ybiPvMKoEIe3ih9F',  // _DSC2106.JPG
  'https://lh3.googleusercontent.com/d/1lsYnEMViLU3A9lKzvDbCT6woMFLKry2V',  // _DSC2107.JPG
  'https://lh3.googleusercontent.com/d/15jXXfRiGhUT_7oAXUrCv0Pud-SCRusxX',  // _DSC2108.JPG
  'https://lh3.googleusercontent.com/d/1wDoPxDhbnM6aGqBz0nhgl_1_1d8D9RMF',  // _DSC2109.JPG
  'https://lh3.googleusercontent.com/d/1ebdkdDbbBt_hQFzh0zUJOVHITy6bBNlv',  // _DSC2111.JPG
  'https://lh3.googleusercontent.com/d/1ems72eR7RC3aKoxQsFkPOjRISTmrB6X1',  // _DSC2112.JPG
  'https://lh3.googleusercontent.com/d/1yC6mgP_Nz9DVktU7K6S3lSHta9NvT_SX',  // _DSC2113.JPG
  'https://lh3.googleusercontent.com/d/19FujGKB21AFMD54kSgemedXW8VTAWCiK',  // _DSC2114.JPG
  'https://lh3.googleusercontent.com/d/1nliuPHw2dtZdBM2Qw-WkpYgGBJorl0Jz',  // _DSC2115.JPG
  'https://lh3.googleusercontent.com/d/1pDIEuJyHQwkOg6Gt5_sGgohmhvLU4qBv',  // _DSC2116.JPG
  'https://lh3.googleusercontent.com/d/1mDTBKgSxCaverKgDIOlNja_dfpSnTpKz',  // _DSC2117.JPG
  'https://lh3.googleusercontent.com/d/1KTkUynGEs2LmAwzgRJadpsLJ5SptNiAY',  // _DSC2118.JPG
  'https://lh3.googleusercontent.com/d/1nsboTmA6cdd4dTwFU8WJl1fXbuOh63A6',  // _DSC2121.JPG
  'https://lh3.googleusercontent.com/d/1AWlvfvyKGwttGNZzDdy_4KIXm08lHkUP',  // _DSC2122.JPG
  'https://lh3.googleusercontent.com/d/1AUfdzmsAdP31L8DYRNT92Odu0xpHuZCV',  // _DSC2123.JPG
  'https://lh3.googleusercontent.com/d/1NXaOawpC69sEcEERNZIVYVvmNqIdNORD',  // _DSC2124.JPG
  'https://lh3.googleusercontent.com/d/1Q5jzebBqno3MbXc3TvZnENo06e1lFOec',  // _DSC2125.JPG
  'https://lh3.googleusercontent.com/d/1cqJxnv5duwopAyIf-5pk2TVAXDJy_bB8',  // _DSC2126.JPG
  'https://lh3.googleusercontent.com/d/1h3gqL_RRPUtsaMmYH3ZTB7f1gURgMwOm',  // _DSC2128.JPG
  'https://lh3.googleusercontent.com/d/1VW_0ccAkBs2fiYF1lCyFhdvenhk14khf',  // _DSC2130.JPG
  'https://lh3.googleusercontent.com/d/17FxQBHenWmWHV3Q_NFVMz7km7acVmj3R',  // _DSC2131.JPG
  'https://lh3.googleusercontent.com/d/1LLpjyf8_Zmo-RloqJebniraFVk2go7Wp',  // _DSC2132.JPG
  'https://lh3.googleusercontent.com/d/170J0NeVUAgm9C3xVerzaHyslFZBB_7e3',  // _DSC2133.JPG
  'https://lh3.googleusercontent.com/d/1GP6DpiXxltsLQCoWB4TbNotXO2gWaNAg',  // _DSC2134.JPG
  'https://lh3.googleusercontent.com/d/1asD9q4GE4eaW0TPz9FI8QaBugUecjwvM',  // _DSC2137.JPG
  'https://lh3.googleusercontent.com/d/14fxjsfUaff6hxtaHbp3rfln0YkghKm5_',  // _DSC2138.JPG
  'https://lh3.googleusercontent.com/d/1RLmzZCfS-FRw97Vq4T8WTVugfS1OWX-1',  // _DSC2139.JPG
  'https://lh3.googleusercontent.com/d/1MqHyGz0jBSEUhJCQep4PkqEEGi59HJ5c',  // _DSC2140.JPG
  'https://lh3.googleusercontent.com/d/1y3eJcMr_i10EtcHZxOHSDH1AXRtytlMi',  // _DSC2142.JPG
  'https://lh3.googleusercontent.com/d/1sbs2bwkqIVe5tLYAX45Jc4nTEnMUlLT1',  // _DSC2143.JPG
  'https://lh3.googleusercontent.com/d/1hs2ZSnR3fgdMyDWB5gpfgSpieGjP_jOw',  // _DSC2144.JPG
  'https://lh3.googleusercontent.com/d/1J3dNTTHgoQMeYcPkK_LJEWZ7nv4g-EAC',  // _DSC2146.JPG
];

const BATCH   = 30;
let shown     = 0;

const grid    = document.getElementById('galleryGrid');
const countEl = document.getElementById('galleryCount');
const btnMore = document.getElementById('btnLoadMore');
const btnAll  = document.getElementById('btnLoadAll');

function updateCount() {
  countEl.textContent = `Showing ${shown} of ${images.length} photos`;
  btnMore.disabled = shown >= images.length;
  btnAll.disabled  = shown >= images.length;
}

function addItems(start, end) {
  const frag = document.createDocumentFragment();
  for (let i = start; i < end && i < images.length; i++) {
    const item = document.createElement('div');
    item.className = 'gallery-item';

    const img = document.createElement('img');
    img.src      = images[i];
    img.alt      = `Matkor ceremony photo ${i + 1}`;
    img.loading  = 'lazy';
    img.decoding = 'async';
    img.onload  = () => img.classList.add('loaded');
    img.onerror = () => img.classList.add('loaded');

    const overlay = document.createElement('div');
    overlay.className = 'item-overlay';
    overlay.innerHTML = '<span class="zoom-icon">⊕</span>';

    item.appendChild(img);
    item.appendChild(overlay);
    item.addEventListener('click', () => openLightbox(i));
    frag.appendChild(item);
  }
  grid.appendChild(frag);
}

function loadMore() {
  const next = Math.min(shown + BATCH, images.length);
  addItems(shown, next);
  shown = next;
  updateCount();
}

function loadAll() {
  addItems(shown, images.length);
  shown = images.length;
  updateCount();
}

btnMore.addEventListener('click', loadMore);
btnAll.addEventListener('click', loadAll);
loadMore();

// ── Lightbox ──────────────────────────────────────────────────────────
const lightbox      = document.getElementById('lightbox');
const lbImg         = document.getElementById('lb-img');
const lbCounter     = document.getElementById('lb-counter');
const lbClose       = document.getElementById('lb-close');
const lbPrev        = document.getElementById('lb-prev');
const lbNext        = document.getElementById('lb-next');
const lbPlay        = document.getElementById('lb-play');
const lbProgressBar = document.getElementById('lb-progress-bar');
let currentIdx      = 0;

function openLightbox(idx) {
  currentIdx = idx;
  setLbImage(idx);
  lightbox.classList.add('active');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  stopSlideshow();
  resetZoom();
  lightbox.classList.remove('active');
  document.body.style.overflow = '';
}

function setLbImage(idx) {
  lbImg.classList.add('loading');
  const tmp = new Image();
  tmp.onload = () => { lbImg.src = tmp.src; lbImg.classList.remove('loading'); };
  tmp.src = images[idx];
  lbCounter.textContent = `${idx + 1} / ${images.length}`;
}

function lbGo(dir) {
  resetZoom();
  currentIdx = (currentIdx + dir + images.length) % images.length;
  setLbImage(currentIdx);
  if (slideshowActive) restartProgress();
}

lbClose.addEventListener('click', closeLightbox);
lbPrev.addEventListener('click', () => lbGo(-1));
lbNext.addEventListener('click', () => lbGo(1));
lightbox.addEventListener('click', (e) => { if (e.target === lightbox) closeLightbox(); });
document.addEventListener('keydown', (e) => {
  if (!lightbox.classList.contains('active')) return;
  if (e.key === 'Escape')     closeLightbox();
  if (e.key === 'ArrowLeft')  lbGo(-1);
  if (e.key === 'ArrowRight') lbGo(1);
  if (e.key === ' ')          toggleSlideshow();
});

// ── Slideshow ─────────────────────────────────────────────────────────
const SLIDESHOW_MS  = 3500;
let slideshowActive = false;
let slideshowTimer  = null;

function startSlideshow() {
  slideshowActive = true;
  lbPlay.classList.add('playing');
  lbPlay.innerHTML = '&#9646;&#9646;';
  lbPlay.setAttribute('aria-label', 'Pause slideshow');
  restartProgress();
}

function stopSlideshow() {
  slideshowActive = false;
  clearTimeout(slideshowTimer);
  lbPlay.classList.remove('playing');
  lbPlay.innerHTML = '&#9654;';
  lbPlay.setAttribute('aria-label', 'Play slideshow');
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
}

function toggleSlideshow() { slideshowActive ? stopSlideshow() : startSlideshow(); }

function restartProgress() {
  clearTimeout(slideshowTimer);
  lbProgressBar.style.transition = 'none';
  lbProgressBar.style.width = '0%';
  void lbProgressBar.offsetWidth;
  lbProgressBar.style.transition = `width ${SLIDESHOW_MS}ms linear`;
  lbProgressBar.style.width = '100%';
  slideshowTimer = setTimeout(() => { if (slideshowActive) lbGo(1); }, SLIDESHOW_MS);
}

lbPlay.addEventListener('click', toggleSlideshow);

// ── Pinch-to-Zoom & Pan ───────────────────────────────────────────────
let scale = 1, panX = 0, panY = 0;
let isPinching = false, initDist = 0, initScale = 1;
let isDragging = false, dragStartX = 0, dragStartY = 0, dragPanX = 0, dragPanY = 0;
let lastTap = 0;

function applyTransform(animated) {
  if (animated) { lbImg.style.transition = 'transform 0.25s ease'; setTimeout(() => { lbImg.style.transition = ''; }, 260); }
  else { lbImg.style.transition = ''; }
  lbImg.style.transform = `translate(${panX}px, ${panY}px) scale(${scale})`;
  lbImg.classList.toggle('zoomed', scale > 1);
}

function resetZoom() {
  scale = 1; panX = 0; panY = 0;
  lbImg.style.transition = 'transform 0.25s ease';
  lbImg.style.transform = '';
  lbImg.classList.remove('zoomed', 'dragging');
  setTimeout(() => { lbImg.style.transition = ''; }, 260);
}

function getDist(t) { return Math.hypot(t[0].clientX - t[1].clientX, t[0].clientY - t[1].clientY); }

lbImg.addEventListener('touchstart', (e) => {
  if (e.touches.length === 2) {
    isPinching = true; isDragging = false;
    initDist = getDist(e.touches); initScale = scale; e.preventDefault();
  } else if (e.touches.length === 1) {
    const now = Date.now();
    if (now - lastTap < 280) { lastTap = 0; scale > 1 ? resetZoom() : (scale = 2.5, applyTransform(true)); e.preventDefault(); return; }
    lastTap = now;
    if (scale > 1) { isDragging = true; dragStartX = e.touches[0].clientX; dragStartY = e.touches[0].clientY; dragPanX = panX; dragPanY = panY; lbImg.classList.add('dragging'); e.preventDefault(); }
  }
}, { passive: false });

lbImg.addEventListener('touchmove', (e) => {
  if (isPinching && e.touches.length === 2) { scale = Math.min(Math.max(initScale * (getDist(e.touches) / initDist), 1), 4); applyTransform(false); e.preventDefault(); }
  else if (isDragging && e.touches.length === 1 && scale > 1) { panX = dragPanX + (e.touches[0].clientX - dragStartX); panY = dragPanY + (e.touches[0].clientY - dragStartY); applyTransform(false); e.preventDefault(); }
}, { passive: false });

lbImg.addEventListener('touchend', (e) => {
  if (e.touches.length < 2) isPinching = false;
  if (e.touches.length === 0) { isDragging = false; lbImg.classList.remove('dragging'); if (scale < 1.08) resetZoom(); }
});

let swipeStartX = 0, swipeStartY = 0;
lightbox.addEventListener('touchstart', (e) => { if (e.target === lbImg) return; swipeStartX = e.touches[0].clientX; swipeStartY = e.touches[0].clientY; }, { passive: true });
lightbox.addEventListener('touchend', (e) => {
  if (e.target === lbImg || scale > 1) return;
  const dx = e.changedTouches[0].clientX - swipeStartX;
  const dy = e.changedTouches[0].clientY - swipeStartY;
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) lbGo(dx < 0 ? 1 : -1);
});
